# syntax = docker/dockerfile:experimental
FROM 912288704264.dkr.ecr.us-east-1.amazonaws.com/shared/python:3.8

ENV PYTHONUNBUFFERED 1
ARG DEPLOYMENT_ENV=dev

RUN apt-get update && apt-get install -y --no-install-recommends \
  postgresql-client \
  libmemcached-dev \
  libz-dev

# install NVM
ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 5.6.0

RUN mkdir $NVM_DIR
RUN curl https://raw.githubusercontent.com/creationix/nvm/v0.37.2/install.sh | bash \
  && . $NVM_DIR/nvm.sh \
  && nvm install $NODE_VERSION \
  && nvm alias default $NODE_VERSION \
  && nvm use default

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

COPY . /app/
WORKDIR /app

RUN pip install -r pip/requirements.txt

# Compile front-end dependencies
RUN npm install
RUN npm run build

RUN mv compose/$DEPLOYMENT_ENV/django/entrypoint entrypoint
RUN chmod +x entrypoint

EXPOSE 5000/tcp
ENTRYPOINT ["/app/entrypoint"]
