# syntax = docker/dockerfile:experimental
FROM public.ecr.aws/bitnami/python:3.8

ENV PYTHONUNBUFFERED 1
ARG DEPLOYMENT_ENV=dev

ARG AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID

ARG AWS_SECRET_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY

ARG REDIS_URL
ENV REDIS_URL $REDIS_URL

ARG POSTGRES_USER
ENV POSTGRES_USER $POSTGRES_USER

ARG POSTGRES_DB
ENV POSTGRES_DB $POSTGRES_DB

ARG POSTGRES_PASSWORD
ENV POSTGRES_PASSWORD $POSTGRES_PASSWORD

ARG POSTGRES_HOST
ENV POSTGRES_HOST $POSTGRES_HOST

ARG POSTGRES_PORT
ENV POSTGRES_PORT $POSTGRES_PORT

ARG SQUARELET_KEY
ENV SQUARELET_KEY $SQUARELET_KEY

ARG SQUARELET_SECRET
ENV SQUARELET_SECRET $SQUARELET_SECRET

ARG SQUARELET_URL
ENV SQUARELET_URL $SQUARELET_URL

ARG STRIPE_PUB_KEY
ENV STRIPE_PUB_KEY $STRIPE_PUB_KEY

ARG STRIPE_SECRET_KEY
ENV STRIPE_SECRET_KEY $STRIPE_SECRET_KEY

RUN apt-get update && apt-get install -y --no-install-recommends \
  postgresql-client \
  libmemcached-dev \
  libz-dev

# install NVM
ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 5.6.0

RUN mkdir $NVM_DIR
RUN curl https://raw.githubusercontent.com/creationix/nvm/v0.37.2/install.sh | bash \
  && . $NVM_DIR/nvm.sh \
  && nvm install $NODE_VERSION \
  && nvm alias default $NODE_VERSION \
  && nvm use default

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

COPY . /app/

# Compile front-end dependencies
RUN npm install
RUN npm run build

# Requirements are installed here to ensure they will be cached.
RUN pip install -r pip/requirements.txt
WORKDIR /app

RUN mv compose/$DEPLOYMENT_ENV/django/entrypoint entrypoint
RUN chmod +x entrypoint

EXPOSE 5000/tcp

ENTRYPOINT ["/app/entrypoint"]
