# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 14:26
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('crowdsource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdsourcechoice',
            name='value',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crowdsourcefield',
            name='help_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
