# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 14:55
from __future__ import unicode_literals

from django.db import migrations


def set_value(apps, schema_editor):
    """Set the value for choices to the choice label"""
    CrowdsourceChoice = apps.get_model('crowdsource', 'CrowdsourceChoice')
    for choice in CrowdsourceChoice.objects.all():
        choice.value = choice.choice
        choice.save()


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsource', '0002_auto_20180110_1426'),
    ]

    operations = [
        migrations.RunPython(set_value, migrations.RunPython.noop),
    ]
