# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 16:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsource', '0003_auto_20180110_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdsourcedata',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='crowdsourcedata',
            name='url',
            field=models.URLField(max_length=255, verbose_name=b'Data URL'),
        ),
    ]
