# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsource', '0009_auto_20180125_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdsourcevalue',
            name='value',
            field=models.CharField(max_length=2000),
        ),
    ]
