# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-11 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsource', '0013_auto_20180402_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdsource',
            name='submission_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
