# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-17 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0010_auto_20180307_1306'),
        ('crowdsource', '0014_crowdsource_submission_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crowdsource',
            name='submission_email',
        ),
        migrations.AddField(
            model_name='crowdsource',
            name='submission_emails',
            field=models.ManyToManyField(to='communication.EmailAddress'),
        ),
    ]
