# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-30 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_remove_tag_user'),
        ('crowdsource', '0016_crowdsourceresponse_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdsourcefield',
            name='gallery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crowdsourceresponse',
            name='gallery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crowdsourceresponse',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tags.TaggedItemBase', to='tags.Tag', verbose_name='Tags'),
        ),
    ]
