# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 19:04

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsource', '0021_auto_20180905_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdsource',
            name='featured',
            field=models.BooleanField(
                default=False,
                help_text='Featured assignments will appear on the homepage.'
            ),
        ),
    ]
