# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-18 18:24

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsource', '0022_crowdsource_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdsourcefield',
            name='type',
            field=models.CharField(
                choices=[('text', 'text'), ('select', 'select'),
                         ('checkbox2',
                          'checkbox2'), ('checkbox-group',
                                         'checkbox-group'), ('date', 'date'),
                         ('number', 'number'), ('textarea', 'textarea')],
                max_length=15
            ),
        ),
    ]
