# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-18 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsource', '0022_crowdsource_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdsourcefield',
            name='type',
            field=models.CharField(choices=[(b'text', b'text'), (b'select', b'select'), (b'checkbox2', b'checkbox2'), (b'checkbox-group', b'checkbox-group'), (b'date', b'date'), (b'number', b'number'), (b'textarea', b'textarea')], max_length=15),
        ),
    ]
