# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-08 19:35

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsource', '0023_auto_20190718_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdsourceresponse',
            name='public',
            field=models.BooleanField(
                default=False,
                help_text=
                'Publically credit the user who submitted this response in the gallery'
            ),
        ),
    ]
