# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-09 21:47

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsource', '0024_crowdsourceresponse_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdsourcefield',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crowdsourcefield',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crowdsourcefield',
            name='type',
            field=models.CharField(
                choices=[('text', 'text'), ('select', 'select'),
                         ('checkbox2',
                          'checkbox2'), ('checkbox-group', 'checkbox-group'),
                         ('date', 'date'), ('number',
                                            'number'), ('textarea', 'textarea'),
                         ('header', 'header'), ('paragraph', 'paragraph')],
                max_length=15
            ),
        ),
    ]
