# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-09 21:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsource', '0024_crowdsourceresponse_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdsourcefield',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crowdsourcefield',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crowdsourcefield',
            name='type',
            field=models.CharField(choices=[(b'text', b'text'), (b'select', b'select'), (b'checkbox2', b'checkbox2'), (b'checkbox-group', b'checkbox-group'), (b'date', b'date'), (b'number', b'number'), (b'textarea', b'textarea'), (b'header', b'header'), (b'paragraph', b'paragraph')], max_length=15),
        ),
    ]
