# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-07 18:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsource', '0026_crowdsource_ask_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdsource',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crowdsources', to='project.Project'),
        ),
        migrations.AlterField(
            model_name='crowdsource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crowdsources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crowdsourceresponse',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='crowdsource.CrowdsourceData'),
        ),
        migrations.AlterField(
            model_name='crowdsourceresponse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crowdsource_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
