# Generated by Django 2.2.15 on 2020-11-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsource', '0027_auto_20200707_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdsourcedata',
            name='url',
            field=models.URLField(blank=True, max_length=255, verbose_name='Data URL'),
        ),
    ]
