# Generated by Django 3.2.9 on 2021-12-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsource', '0028_auto_20201124_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdsourcedata',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
