# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-11 09:13
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20160215_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=b'news_images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to=b'news_photos/%Y/%m/%d'),
        ),
    ]
