# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 18:06
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20170423_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=b'news_images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Publish date'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to=b'news_photos/%Y/%m/%d'),
        ),
    ]
