# Generated by Django 3.2.9 on 2022-03-15 18:22

# Django
from django.db import migrations


def add_order(apps, schema_editor):
    Article = apps.get_model("news", "Article")
    Authorship = apps.get_model("news", "Authorship")

    authorships = []
    for article in Article.objects.prefetch_related("authors"):
        authorships.extend(
            [
                Authorship(article=article, author=author)
                for author in article.authors.all()
            ]
        )
    Authorship.objects.bulk_create(authorships)


def remove_order(apps, schema_editor):
    Article = apps.get_model("news", "Article")
    Authorship = apps.get_model("news", "Authorship")

    for author in Authorship.objects.select_related("article", "author"):
        author.article.authors.add(author.author)


class Migration(migrations.Migration):

    dependencies = [("news", "0009_auto_20220315_1422")]

    operations = [migrations.RunPython(add_order, remove_order)]
