# Generated by Django 3.2.9 on 2022-03-15 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20220315_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorship',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='authors',
            new_name='authors_old',
        ),
    ]
