# Generated by Django 3.2.9 on 2022-03-15 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20220315_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='authors_new',
            new_name='authors',
        ),
    ]
