# Generated by Django 3.2.9 on 2022-03-15 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0012_rename_authors_new_article_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(related_name='authored_articles', through='news.Authorship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='authors_old',
            field=models.ManyToManyField(related_name='authored_articles_old', to=settings.AUTH_USER_MODEL),
        ),
    ]
