# Generated by Django 3.2.9 on 2022-03-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20220315_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='authors_old',
        ),
    ]
