# Generated by Django 3.2.9 on 2022-09-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_remove_article_authors_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scrollama',
            field=models.BooleanField(default=False, help_text='Enable the scrollama javascript library for this article', verbose_name='Use scrollama'),
        ),
    ]
