# Generated by Django 3.2.9 on 2022-10-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_article_scrollama'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sidebar',
            field=models.BooleanField(default=True, verbose_name='Show the sidebar'),
        ),
    ]
