# Generated by Django 3.2.9 on 2023-01-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_article_sidebar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='A "Slug" is a unique URL-friendly title for an object.', max_length=200, unique=True),
        ),
    ]
