# Generated by Django 4.2 on 2023-07-31 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0019_homepageoverride_image_override_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepageoverride",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepageoverride",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="news.article",
            ),
        ),
    ]
