# Generated by Django 4.2 on 2023-08-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0020_homepageoverride_url_alter_homepageoverride_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepageoverride",
            name="pub_date_override",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Publish date"
            ),
        ),
    ]
