# Generated by Django 4.2 on 2023-08-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0021_alter_homepageoverride_pub_date_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepageoverride",
            name="hide_date",
            field=models.BooleanField(default=False),
        ),
    ]
