# Generated by Django 4.2 on 2023-10-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0023_article_image_alt_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepageoverride",
            name="image_alt_text_override",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
