# Generated by Django 4.2 on 2025-07-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0024_homepageoverride_image_alt_text_override"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HomepageOverride",
        ),
    ]
