"""
Constants for the FOIA app
"""

# submit a composer with a 35 minute delay
COMPOSER_SUBMIT_DELAY = 35 * 60

# allow a composer to be edited 30 minutes after it has been submitted
COMPOSER_EDIT_DELAY = 30 * 60

# elements allowed in html email, from:
# https://www.pinpointe.com/blog/email-campaign-html-and-css-support
EMAIL_TAGS = [
    "a",
    "b",
    "br",
    "div",
    "font",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "head",
    "hr",
    "img",
    "label",
    "li",
    "ol",
    "p",
    "span",
    "strong",
    "table",
    "td",
    "th",
    "tr",
    "u",
    "ul",
]
EMAIL_ATTRIBUTES = {
    "a": ["class", "href", "id", "style", "target"],
    "b": ["class", "id", "style"],
    "br": ["class", "id", "style"],
    "div": ["align", "class", "dir", "id", "style"],
    "font": ["class", "color", "face", "id", "size", "style"],
    "h1": ["align", "class", "dir", "id", "style"],
    "h2": ["align", "class", "dir", "id", "style"],
    "h3": ["align", "class", "dir", "id", "style"],
    "h4": ["align", "class", "dir", "id", "style"],
    "h5": ["align", "class", "dir", "id", "style"],
    "h6": ["align", "class", "dir", "id", "style"],
    "head": ["dir", "lang"],
    "hr": ["align", "size", "width"],
    "img": [
        "align",
        "border",
        "class",
        "height",
        "hspace",
        "id",
        "src",
        "style",
        "usemap",
        "vspace",
        "width",
    ],
    "label": ["class", "id", "style"],
    "li": ["class", "dir", "id", "style", "type"],
    "ol": ["class", "dir", "id", "style", "type"],
    "p": ["align", "class", "dir", "id", "style"],
    "span": ["class", "id", "style"],
    "strong": ["class", "id", "style"],
    "table": [
        "align",
        "bgcolor",
        "border",
        "cellpadding",
        "cellspacing",
        "class",
        "dir",
        "frame",
        "id",
        "rules",
        "style",
        "width",
    ],
    "td": [
        "abbr",
        "align",
        "bgcolor",
        "class",
        "colspan",
        "dir",
        "height",
        "id",
        "lang",
        "rowspan",
        "scope",
        "style",
        "valign",
        "width",
    ],
    "th": [
        "abbr",
        "align",
        "background",
        "bgcolor",
        "class",
        "colspan",
        "dir",
        "height",
        "id",
        "lang",
        "scope",
        "style",
        "valign",
        "width",
    ],
    "tr": ["align", "bgcolor", "class", "dir", "id", "style", "valign"],
    "u": ["class", "id", "style"],
    "ul": ["class", "dir", "id", "style"],
}
EMAIL_STYLES = [
    "background",
    "background-color",
    "border",
    "border-bottom",
    "border-bottom-color",
    "border-bottom-style",
    "border-bottom-width",
    "border-color",
    "border-left",
    "border-left-color",
    "border-left-style",
    "border-left-width",
    "border-right",
    "border-right-color",
    "border-right-style",
    "border-right-width",
    "border-style",
    "border-top",
    "border-top-color",
    "border-width",
    "color",
    "display",
    "font",
    "font-family",
    "font-size",
    "font-style",
    "font-variant",
    "font-weight",
    "height",
    "letter-spacing",
    "line-height",
    "list-style-type",
    "padding",
    "padding-bottom",
    "padding-left",
    "padding-right",
    "padding-top",
    "table-layout",
    "text-align",
    "text-decoration",
    "text-indent",
    "text-transform",
    "vertical-align",
]
