name          'garethr-heroku'
version       '0.0.1'
author        'garethr'
license       'Apache License, Version 2.0'
summary       'Module to install the heroku toolbelt'
project_page  'https://github.com/garethr/garethr-heroku'
dependency    'maestrodev/wget'
