# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='newsletter_cta',
            field=models.CharField(blank=True, help_text=b'Should encourage readers to subscribe.', max_length=255, verbose_name=b'Newsletter Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='newsletter_label',
            field=models.CharField(blank=True, help_text=b'Should describe the newsletter.', max_length=100, verbose_name=b'Newsletter Name'),
        ),
    ]
