# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20160412_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approved',
            field=models.BooleanField(default=False, help_text=b'If a project is approved, is is visible to everyone.'),
        ),
    ]
