# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_project_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='private',
            field=models.BooleanField(default=True, help_text=b'If a project is private, it is only visible to its contributors.'),
        ),
    ]
