# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-11 09:13
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20160421_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=b'project_images/%Y/%m/%d'),
        ),
    ]
