# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-15 09:34
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20170423_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(help_text=b'The slug is automatically generated based on the title.', max_length=255),
        ),
    ]
