# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-12 14:15
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20170615_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_approved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
