# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-12 14:17
from __future__ import unicode_literals

import datetime
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20180112_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
