# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 13:53
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20180112_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=b'project_images/%Y/%m/%d'),
        ),
    ]
