# Generated by Django 2.2.15 on 2020-09-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20180122_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/%Y/%m/%d'),
        ),
    ]
