version: '3.8'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  muckrock_django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
      network: host
    image: muckrock_local_django
    depends_on:
      - muckrock_redis
      - muckrock_postgres
    volumes:
      - .:/app
      - ~/.netrc:/root/.netrc
    environment:
      - IPYTHONDIR=/app/.ipython
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: /start
    networks:
      default:
        aliases:
          - internal.dev.muckrock.com
          - internal.dev.foiamachine.org
      squarelet_default:
        aliases:
          - internal.dev.muckrock.com
          - internal.dev.foiamachine.org

  muckrock_postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: muckrock_production_postgres
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    env_file:
      - ./.envs/.local/.postgres

  muckrock_redis:
    image: redis:3.2

  muckrock_celeryworker:
    <<: *django
    image: muckrock_local_celeryworker
    depends_on:
      - muckrock_redis
      - muckrock_postgres
    command: /start-celeryworker
    environment:
      - C_FORCE_ROOT=true
    networks:
      default:
        aliases: []
      squarelet_default:
        aliases: []

  muckrock_celerybeat:
    <<: *django
    image: muckrock_local_celerybeat
    depends_on:
      - muckrock_redis
      - muckrock_postgres
    command: /start-celerybeat
    networks:
      default:
        aliases: []
      squarelet_default:
        aliases: []

networks:
  squarelet_default:
    external: true
