version: '3.8'
name: ${COMPOSE_PROJECT_NAME:-muckrock}

volumes:
  postgres15_data_local: {}
  postgres15_backup_local: {}
  foia_coach_postgres_data_local: {}

services:
  muckrock_django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
      network: host
    image: muckrock_local_django
    depends_on:
      - muckrock_redis
      - muckrock_postgres
    ports:
      - "8000:80"
    volumes:
      - .:/app
      - ~/.netrc:/root/.netrc
    environment:
      - IPYTHONDIR=/app/.ipython
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: /start
    networks:
      default:
        aliases:
          - internal.dev.muckrock.com
          - internal.dev.foiamachine.org
      squarelet_default:
        aliases:
          - internal.dev.muckrock.com
          - internal.dev.foiamachine.org

  foia_coach_api:
    build:
      context: ./foia-coach-api
      dockerfile: ./compose/local/Dockerfile
    image: muckrock_foia_coach_api_local
    container_name: foia_coach_api_local
    depends_on:
      - foia_coach_postgres
    volumes:
      - ./foia-coach-api:/app:z
    env_file:
      - ./.envs/.local/.foia_coach_postgres
      - ./.envs/.local/.foia_coach_api
    environment:
      # Explicitly set database connection to override any inherited env vars
      - POSTGRES_HOST=foia_coach_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=foia_coach
      - POSTGRES_USER=foia_coach_user
      - POSTGRES_PASSWORD=foia_coach_dev_password_change_in_production
    ports:
      - "8001:8000"
    command: /start
    networks:
      - default

  foia_coach_postgres:
    image: postgres:15-alpine
    container_name: foia_coach_postgres_local
    volumes:
      - foia_coach_postgres_data_local:/var/lib/postgresql/data
    env_file:
      - ./.envs/.local/.foia_coach_postgres
    ports:
      - "5433:5432"

  muckrock_postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile15
    image: muckrock_production_postgres15
    volumes:
      - postgres15_data_local:/var/lib/postgresql/data
      - postgres15_backup_local:/backups
    env_file:
      - ./.envs/.local/.postgres

  muckrock_redis:
    image: redis:3.2

  muckrock_celeryworker:
    <<: *django
    image: muckrock_local_celeryworker
    depends_on:
      - muckrock_redis
      - muckrock_postgres
    ports: []
    command: /start-celeryworker
    environment:
      - C_FORCE_ROOT=true
    networks:
      default:
        aliases: []
      squarelet_default:
        aliases: []

  muckrock_celerybeat:
    <<: *django
    image: muckrock_local_celerybeat
    depends_on:
      - muckrock_redis
      - muckrock_postgres
    ports: []
    command: /start-celerybeat
    networks:
      default:
        aliases: []
      squarelet_default:
        aliases: []

networks:
  squarelet_default:
    external: true
