# Generated by Django 4.2 on 2025-07-17 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0024_homepageoverride_image_alt_text_override"),
        ("project", "0018_auto_20200901_1327"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about_heading",
                    models.CharField(
                        default="We give you the tools to keep government transparent and accountable",
                        max_length=255,
                    ),
                ),
                (
                    "about_paragraph",
                    models.TextField(
                        blank=True,
                        default="MuckRock Foundation is a nonprofit, collaborative organization and newsroom that brings together journalists, researchers and the public to request, analyze and share government information, making politics more transparent and democracy more informed.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page",
                "verbose_name_plural": "Home Page",
            },
        ),
        migrations.CreateModel(
            name="FeaturedProjectSlot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order of appearance on homepage"
                    ),
                ),
                (
                    "articles",
                    models.ManyToManyField(
                        blank=True, related_name="featured_in_slots", to="news.article"
                    ),
                ),
                (
                    "homepage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_project_slots",
                        to="core.homepage",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_slots",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Featured Project Slot",
                "verbose_name_plural": "Featured Project Slots",
                "ordering": ["order"],
            },
        ),
    ]
