# Generated by Django 4.2 on 2025-07-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_homepage_featuredprojectslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="product_stats",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON object for DocumentCloud and Data Liberation Project stats",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="expertise_sections",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="JSON array of expertise sections, each with title, subtitle, description, and links (title, href, text, icon)",
            ),
        ),
    ]
