# Generated by Django 4.2 on 2025-07-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_homepage_featuredprojectslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="product_stats",
            field=models.TextField(
                blank=True,
                default='{"documentcloud": {"documents": 0, "pages": 0, "notes": 0}, "dataliberation": {"participants": 0, "datasets": 0}}',
                help_text="JSON object for DocumentCloud and Data Liberation Project stats",
            ),
        ),
    ]
