# Generated by Django 4.2 on 2025-07-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_homepage_product_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="expertise_sections",
            field=models.TextField(
                blank=True,
                default="[]",
                help_text="JSON array of expertise sections, each with title, subtitle, description, and links (title, href, text, icon)",
            ),
        ),
    ]
