# Generated by Django 4.2 on 2025-08-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_homepage_product_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="dlp_stats",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON object for Data Liberation Project stats",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="documentcloud_stats",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON object for latest DocumentCloud stats",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="expertise_sections",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "JSON array of expertise sections, each with title, subtitle, description, and links (title, href, text, icon)",
                ),
            ),
        ),
    ]
