# Generated by Django 4.2 on 2025-09-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_homepage_product_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveButterCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(default='g6R32g', help_text="GiveButter campaign ID (e.g., 'g6R32g')", max_length=50)),
            ],
            options={
                'verbose_name': 'GiveButter Campaign',
                'verbose_name_plural': 'GiveButter Campaign',
            },
        ),
        migrations.AlterField(
            model_name='homepage',
            name='expertise_sections',
            field=models.JSONField(blank=True, default=list, help_text=('JSON array of expertise sections, each with title, subtitle, description, and links (title, href, text, icon)',)),
        ),
    ]
