# Generated by Django 4.2 on 2025-08-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_split_stats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="product_stats",
        ),
    ]
