# Generated by Django 4.2 on 2025-10-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_homepage_product_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_message',
            field=models.TextField(blank=True, default='', help_text='Site-wide banner message. Supports Markdown. Will be shown at the top of all pages. Users can dismiss it.'),
        ),
    ]
