# Generated by Django 5.2.11 on 2026-04-28 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("managing", "Managing this request"),
                            ("communications", "Communications and messages"),
                            ("payments", "Checks and request payments"),
                            ("documents", "Documents and files"),
                            ("portals", "Agency portals and web forms"),
                            ("appeals", "Appeals and public records advice"),
                            ("proxy", "In-state proxy and proof of citizenship"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("resolution", models.TextField(blank=True)),
                (
                    "flag_category",
                    models.CharField(
                        blank=True,
                        help_text="Maps to an existing flag category for staff triage",
                        max_length=40,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="gethelp.problem",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "order"],
            },
        ),
    ]
