# Generated by Django 5.2.12 on 2026-05-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gethelp", "0003_problem_category_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="placeholder",
            field=models.CharField(
                blank=True,
                help_text="Placeholder text for the free-form contact textarea when this category is selected. Leave blank to use the site default.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="placeholder",
            field=models.CharField(
                blank=True,
                help_text="Placeholder text for the free-form contact textarea when this problem is selected. Overrides the category placeholder. Leave blank to fall back to the category or site default.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
