# Generated by Django 5.2.12 on 2026-05-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gethelp", "0004_category_placeholder_problem_placeholder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional intro shown above the list of problems in this category.",
            ),
        ),
    ]
