# Generated by Django 5.2.12 on 2026-05-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gethelp", "0005_category_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                help_text='Optional intro shown above the list of problems in this category. Supports Markdown — see the <a href="https://daringfireball.net/projects/markdown/syntax" target="_blank" rel="noopener">syntax guide</a>.',
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="resolution",
            field=models.TextField(
                blank=True,
                help_text='How the user can resolve this problem on their own. Supports Markdown — see the <a href="https://daringfireball.net/projects/markdown/syntax" target="_blank" rel="noopener">syntax guide</a>.',
            ),
        ),
    ]
