# Generated by Django 5.2.12 on 2026-05-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gethelp", "0006_alter_category_description_alter_problem_resolution"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.AlterField(
            model_name="category",
            name="label",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
