HOSTS:
  'debian-8-vcloud':
    roles:
      - master
    platform: debian-8-x86
    hypervisor: vcloud
    template: debian-8-i386
CONFIG:
  type: foss
  ssh:
    keys: "~/.ssh/id_rsa-acceptance"
  datastore: instance0
  folder: Delivery/Quality Assurance/Enterprise/Dynamic
  resourcepool: delivery/Quality Assurance/Enterprise/Dynamic
  pooling_api: http://vcloud.delivery.puppetlabs.net/

