# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-16 17:12


# Django
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0004_organization_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                ('active', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='uuid',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='monthly_requests',
            field=models.IntegerField(
                db_column=b'monthly_requests', default=50
            ),
        ),
        migrations.AddField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='memberships',
                to='organization.Organization'
            ),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='memberships',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(
                related_name='organizations',
                through='organization.Membership',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([('user', 'organization')]),
        ),
    ]
