# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-16 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20181016_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='monthly_requests',
            new_name='_monthly_requests',
        ),
        migrations.AlterField(
            model_name='organization',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
