# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-30 18:03

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_auto_22261225_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='org_type',
        ),
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.IntegerField(
                choices=[(0, 'free'), (1, 'pro'), (2, 'basic'), (3, 'plus')],
                default=0
            ),
        ),
    ]
