# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-11 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_auto_20181211_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='requests_per_month',
            field=models.IntegerField(default=0),
        ),
    ]
