# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-11 15:06


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_auto_20181211_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='num_requests',
            new_name='monthly_requests',
        ),
        migrations.AddField(
            model_name='organization',
            name='number_requests',
            field=models.IntegerField(default=0),
        ),
    ]
