# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-12 16:49
from __future__ import unicode_literals

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_auto_20181211_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
