# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-07 19:23
from __future__ import unicode_literals

# Django
from django.db import migrations

PLANS = [
    {
        "name": "Free",
        "slug": "free",
        "minimum_users": 1,
        "base_requests": 0,
        "requests_per_user": 0,
        "feature_level": 0,
    },
    {
        "name": "Professional",
        "slug": "professional",
        "minimum_users": 1,
        "base_requests": 20,
        "requests_per_user": 0,
        "feature_level": 1,
    },
    {
        "name": "Organization",
        "slug": "organization",
        "minimum_users": 5,
        "base_requests": 50,
        "requests_per_user": 5,
        "feature_level": 2,
    },
    {
        "name": "Organization Plus",
        "slug": "organization-plus",
        "minimum_users": 5,
        "base_requests": 50,
        "requests_per_user": 5,
        "feature_level": 2,
    },
    {
        "name": "Admin",
        "slug": "admin",
        "minimum_users": 1,
        "base_requests": 500,
        "requests_per_user": 0,
        "feature_level": 2,
    },
    {
        "name": "Beta",
        "slug": "beta",
        "minimum_users": 1,
        "base_requests": 5,
        "requests_per_user": 0,
        "feature_level": 1,
    },
    {
        "name": "Proxy",
        "slug": "proxy",
        "minimum_users": 1,
        "base_requests": 20,
        "requests_per_user": 0,
        "feature_level": 1,
    },
    {
        "name": "Manual Pay Organization",
        "slug": "manual-pay-organization",
        "minimum_users": 5,
        "base_requests": 50,
        "requests_per_user": 5,
        "feature_level": 2,
    },
]


def add_plans(apps, schema_editor):
    Plan = apps.get_model("organization", "Plan")
    for plan in PLANS:
        Plan.objects.create(**plan)


def remove_plans(apps, schema_editor):
    Plan = apps.get_model("organization", "Plan")
    Plan.objects.all().delete()


def migrate_plans(apps, schema_editor):
    Organization = apps.get_model("organization", "Organization")
    Plan = apps.get_model("organization", "Plan")

    Organization.objects.filter(plan=0).update(
        new_plan=Plan.objects.get(slug='free')
    )
    Organization.objects.filter(plan=1).update(
        new_plan=Plan.objects.get(slug='professional')
    )
    Organization.objects.filter(plan=2).update(
        new_plan=Plan.objects.get(slug='organization')
    )
    Organization.objects.filter(plan=3).update(
        new_plan=Plan.objects.get(slug='organization-plus')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_auto_20190107_1422'),
    ]

    operations = [
        migrations.RunPython(add_plans, remove_plans),
        migrations.RunPython(migrate_plans, migrations.RunPython.noop),
    ]
