# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-08 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_auto_20190107_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='plan',
        ),
    ]
