# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-11 16:01


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_auto_20190108_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='card',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='individual',
            field=models.BooleanField(default=True),
        ),
    ]
