# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-01 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0022_auto_20190111_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='payment_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name=b'UUID'),
        ),
    ]
