# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-07 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0025_auto_20190221_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name=b'UUID'),
        ),
    ]
