# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-08 14:09


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0026_auto_20190307_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
