# Generated by Django 2.2.15 on 2020-08-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0031_auto_20200707_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='active',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='max_users',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='monthly_cost',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='stripe_id',
        ),
    ]
