# Generated by Django 3.2.9 on 2021-12-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0032_auto_20200806_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitlement',
            name='resources',
            field=models.JSONField(default=dict),
        ),
    ]
