# Generated by Django 4.2 on 2023-09-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0033_alter_entitlement_resources"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="verified_journalist",
            field=models.BooleanField(
                default=False,
                help_text="This organization is a verified jorunalistic organization",
            ),
        ),
    ]
