# Generated by Django 4.2 on 2024-04-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0034_organization_verified_journalist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='verified_journalist',
            field=models.BooleanField(default=False, help_text='This organization is a verified journalistic organization'),
        ),
    ]
