# Generated by Django 4.2 on 2025-05-01 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0035_alter_organization_verified_journalist"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="merged",
            field=models.ForeignKey(
                blank=True,
                help_text="The agency this agency was merged in to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="organization.organization",
            ),
        ),
    ]
