# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 18:33

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0004_jurisdiction_requires_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'name',
                    models.CharField(
                        help_text='The common name of the law.', max_length=255
                    )
                ),
                (
                    'shortname',
                    models.CharField(
                        blank=True,
                        help_text=
                        'Abbreviation or acronym, e.g. FOIA, FOIL, OPRA',
                        max_length=20
                    )
                ),
                (
                    'citation',
                    models.CharField(
                        help_text='The legal reference for this law.',
                        max_length=255
                    )
                ),
                (
                    'url',
                    models.URLField(
                        help_text='The URL of the full text of the law.'
                    )
                ),
                ('summary', models.TextField(blank=True)),
                (
                    'jurisdiction',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='laws',
                        to='jurisdiction.Jurisdiction'
                    )
                ),
            ],
        ),
    ]
