# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_remove_tag_user'),
        ('jurisdiction', '0006_jurisdiction_law_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exemption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('basis', models.TextField(help_text=b'The legal or contextual basis for the exemption.')),
                ('appeal_language', models.TextField(help_text=b'Sample language used for appealing the exemption.')),
                ('use_language', models.TextField(blank=True, help_text=b'Sample language used by agencies when invoking the exemption.')),
                ('proper_use', models.TextField(blank=True, help_text=b'An editorialized description of cases when the exemption is properly used.')),
                ('improper_use', models.TextField(blank=True, help_text=b'An editorialized description of cases when the exemption is improperly used.')),
                ('key_citations', models.TextField(blank=True, help_text=b'Significant references to the exemption in caselaw or previous appeals.')),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemptions', to='jurisdiction.Jurisdiction')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tags.TaggedItemBase', to='tags.Tag', verbose_name='Tags')),
            ],
        ),
    ]
