# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 18:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jurisdiction', '0007_exemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemption',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='exemptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
