# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0019_auto_20160330_2039'),
        ('jurisdiction', '0008_exemption_contributors'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvokedExemption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_language', models.TextField(blank=True, help_text=b'What language did the aguency use to invoke the exemption?')),
                ('properly_invoked', models.BooleanField(default=True, help_text=b'Did the agency properly invoke the exemption to the request?')),
                ('appealed', models.BooleanField(default=False, help_text=b'Was the exemption appealed?')),
                ('appeal_language', models.TextField(blank=True, help_text=b'What language was used to appeal?')),
                ('exemption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invokations', to='jurisdiction.Exemption')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foia.FOIARequest')),
            ],
        ),
        migrations.AddField(
            model_name='exemption',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='exemptions', through='jurisdiction.InvokedExemption', to='foia.FOIARequest'),
        ),
    ]
