# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0009_auto_20160802_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField()),
                ('context', models.TextField(blank=True, help_text=b'Under what circumstances is this appeal language most effective?')),
                ('exemption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_appeals', to='jurisdiction.Exemption')),
            ],
        ),
    ]
