# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0009_auto_20161025_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampleappeal',
            name='title',
            field=models.TextField(default=b'Untitled Example'),
        ),
    ]
