# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0010_appeallanguage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exemption',
            name='appeal_language',
        ),
        migrations.RemoveField(
            model_name='exemption',
            name='use_language',
        ),
        migrations.RemoveField(
            model_name='invokedexemption',
            name='appeal_language',
        ),
        migrations.RemoveField(
            model_name='invokedexemption',
            name='appealed',
        ),
    ]
