# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-20 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0010_auto_20161103_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='summary',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Major Dates'),
        ),
    ]
