# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0012_auto_20171005_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurisdiction',
            name='aliases',
            field=models.TextField(blank=True),
        ),
    ]
