# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0016_auto_20180213_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='penalties',
            field=models.BooleanField(default=True),
        ),
    ]
