# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0017_law_penalties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurisdiction',
            name='days',
        ),
        migrations.RemoveField(
            model_name='jurisdiction',
            name='has_appeal',
        ),
        migrations.RemoveField(
            model_name='jurisdiction',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='jurisdiction',
            name='law_analysis',
        ),
        migrations.RemoveField(
            model_name='jurisdiction',
            name='law_name',
        ),
        migrations.RemoveField(
            model_name='jurisdiction',
            name='requires_proxy',
        ),
        migrations.RemoveField(
            model_name='jurisdiction',
            name='use_business_days',
        ),
        migrations.RemoveField(
            model_name='jurisdiction',
            name='waiver',
        ),
    ]
