# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 16:07

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("jurisdiction", "0018_auto_20180214_1443")]

    operations = [
        migrations.CreateModel(
            name="LawYear",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("Enacted", "Enacted"),
                            ("Passed", "Passed"),
                            ("Updated", "Updated"),
                        ],
                        max_length=7,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
            ],
            options={"ordering": ["year"]},
        ),
        migrations.RemoveField(model_name="law", name="intro"),
        migrations.RemoveField(model_name="law", name="summary"),
        migrations.AddField(
            model_name="lawyear",
            name="law",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="years",
                to="jurisdiction.Law",
            ),
        ),
    ]
