# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-12 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0019_auto_20180226_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='cover_executive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='law',
            name='cover_judicial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='law',
            name='cover_legislative',
            field=models.BooleanField(default=False),
        ),
    ]
