# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 15:34


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0020_auto_20180312_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurisdiction',
            name='full_name',
        ),
    ]
