# Generated by Django 2.2.15 on 2021-03-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0023_auto_20200804_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurisdiction',
            name='always_proxy',
            field=models.BooleanField(default=False),
        ),
    ]
