# Generated by Django 3.2.9 on 2021-12-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0024_jurisdiction_always_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invokedexemption',
            name='properly_invoked',
            field=models.BooleanField(default=None, help_text='Did the agency properly invoke the exemption to the request?', null=True),
        ),
    ]
