# Generated by Django 3.2.9 on 2023-01-17 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jurisdiction', '0026_jurisdiction_appeal_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='JurisdictionPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Markdown content for the jurisdiction page')),
                ('jurisdiction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jurisdiction.jurisdiction')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalJurisdictionPage',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('content', models.TextField(help_text='Markdown content for the jurisdiction page')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('jurisdiction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jurisdiction.jurisdiction')),
            ],
            options={
                'verbose_name': 'historical jurisdiction page',
                'verbose_name_plural': 'historical jurisdiction pages',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
