# Generated by Django 3.2.9 on 2023-01-17 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0028_auto_20230117_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljurisdictionpage',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaljurisdictionpage',
            name='jurisdiction',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'level__in': ('s', 'f')}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jurisdiction.jurisdiction'),
        ),
        migrations.AlterField(
            model_name='jurisdictionpage',
            name='jurisdiction',
            field=models.OneToOneField(limit_choices_to={'level__in': ('s', 'f')}, on_delete=django.db.models.deletion.CASCADE, to='jurisdiction.jurisdiction'),
        ),
    ]
