# Generated by Django 4.2 on 2024-05-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jurisdiction", "0029_auto_20230117_1623"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljurisdictionpage",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="jurisdictionpage",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
