# Generated by Django 4.2 on 2026-01-29 20:45

# Django
from django.db import migrations
from django.utils.text import slugify

JURISDICTIONS = [
    "Adjuntas",
    "Aguada",
    "Aguadilla",
    "Aguas Buenas",
    "Aibonito",
    "Arecibo",
    "Arroyo",
    "Añasco",
    "Barceloneta",
    "Barranquitas",
    "Bayamón",
    "Cabo Rojo",
    "Caguas",
    "Camuy",
    "Canóvanas",
    "Carolina",
    "Cataño",
    "Cayey",
    "Ceiba",
    "Ciales",
    "Cidra",
    "Coamo",
    "Comerío",
    "Corozal",
    "Culebra",
    "Dorado",
    "Fajardo",
    "Florida",
    "Guayama",
    "Guayanilla",
    "Guaynabo",
    "Gurabo",
    "Guánica",
    "Hatillo",
    "Hormigueros",
    "Humacao",
    "Isabela",
    "Jayuya",
    "Juana Díaz",
    "Juncos",
    "Lajas",
    "Lares",
    "Las Marías",
    "Las Piedras",
    "Loíza",
    "Luquillo",
    "Manatí",
    "Maricao",
    "Maunabo",
    "Mayagüez",
    "Moca",
    "Morovis",
    "Naguabo",
    "Naranjito",
    "Orocovis",
    "Patillas",
    "Peñuelas",
    "Ponce",
    "Quebradillas",
    "Rincón",
    "Río Grande",
    "Sabana Grande",
    "Salinas",
    "San Germán",
    "San Juan",
    "San Lorenzo",
    "San Sebastián",
    "Santa Isabel",
    "Toa Alta",
    "Toa Baja",
    "Trujillo Alto",
    "Utuado",
    "Vega Alta",
    "Vega Baja",
    "Vieques",
    "Villalba",
    "Yabucoa",
    "Yauco",
]


def add_jurisdictions(apps, schema_editor):
    Jurisdiction = apps.get_model("jurisdiction", "Jurisdiction")
    puerto_rico = Jurisdiction.objects.filter(name="Puerto Rico", level="s").first()
    if puerto_rico is None:
        return
    puerto_rico.waiver = (
        "Los documentos solicitados se pondrán a disposición "
        "del público en general y esta solicitud no se realiza con fines comerciales."
    )
    puerto_rico.save()
    jurisdictions = [
        Jurisdiction(
            name=jurisdiction,
            slug=slugify(jurisdiction),
            level="l",
            parent=puerto_rico,
        )
        for jurisdiction in JURISDICTIONS
    ]
    Jurisdiction.objects.bulk_create(jurisdictions)


def remove_jurisdictions(apps, schema_editor):
    Jurisdiction = apps.get_model("jurisdiction", "Jurisdiction")
    puerto_rico = Jurisdiction.objects.get(name="Puerto Rico", level="s")
    Jurisdiction.objects.filter(parent=puerto_rico, level="l").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("jurisdiction", "0031_alter_jurisdiction_always_proxy_and_more"),
    ]

    operations = [migrations.RunPython(add_jurisdictions, remove_jurisdictions)]
