# Generated by Django 4.2 on 2025-11-26 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jurisdiction", "0031_alter_jurisdiction_always_proxy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeminiFileSearchStore",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(max_length=255, unique=True)),
                ("display_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("total_files", models.PositiveIntegerField(default=0)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Gemini File Search Store",
                "verbose_name_plural": "Gemini File Search Stores",
            },
        ),
        migrations.CreateModel(
            name="JurisdictionResource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Text file containing state-specific FOIA knowledge",
                        upload_to="jurisdiction_resources/%Y/%m/",
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "gemini_file_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gemini_display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "index_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Upload"),
                            ("uploading", "Uploading"),
                            ("indexing", "Indexing"),
                            ("ready", "Ready"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("law_guide", "Law Guide"),
                            ("request_tips", "Request Tips"),
                            ("exemptions", "Exemptions Guide"),
                            ("agency_info", "Agency Information"),
                            ("case_law", "Case Law"),
                            ("general", "General Information"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "jurisdiction",
                    models.ForeignKey(
                        limit_choices_to={"level": "s"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="jurisdiction.jurisdiction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jurisdiction Resource",
                "verbose_name_plural": "Jurisdiction Resources",
                "ordering": ["jurisdiction", "order", "display_name"],
            },
        ),
    ]
