# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 20:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0008_agency_requires_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[(b'primary', b'Primary'), (b'copy', b'Copy'), (b'appeal', b'Appeal'), (b'appeal-copy', b'Appeal Copy'), (b'other', b'Other')], default=b'other', max_length=11)),
            ],
        ),
        migrations.RenameField(
            model_name='agency',
            old_name='user',
            new_name='submitter',
        ),
        migrations.AlterField(
            model_name='agency',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agencyprofile',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Agency'),
        ),
        migrations.AddField(
            model_name='agencyprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agency',
            name='users',
            field=models.ManyToManyField(through='agency.AgencyProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
