# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 10:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_agency_manual_stale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[(b'primary', b'Primary'), (b'appeal', b'Appeal'), (b'none', b'None')], default=b'none', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[(b'primary', b'Primary'), (b'appeal', b'Appeal'), (b'none', b'None')], default=b'none', max_length=7)),
                ('email_type', models.CharField(choices=[(b'to', b'To'), (b'cc', b'CC'), (b'none', b'None')], default=b'none', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[(b'primary', b'Primary'), (b'appeal', b'Appeal'), (b'none', b'None')], default=b'none', max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='agency',
            name='user',
            field=models.ForeignKey(blank=True, help_text=b'The user who submitted this agency', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agencyphone',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Agency'),
        ),
    ]
