# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_auto_20160522_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyprofile',
            name='contact_type',
        ),
        migrations.AddField(
            model_name='agencyprofile',
            name='appeal',
            field=models.CharField(choices=[(b'to', b'Primary'), (b'cc', b'CC'), (b'no', b'None')], default=b'no', max_length=2),
        ),
        migrations.AddField(
            model_name='agencyprofile',
            name='primary',
            field=models.CharField(choices=[(b'to', b'Primary'), (b'cc', b'CC'), (b'no', b'None')], default=b'no', max_length=2),
        ),
    ]
