# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_auto_20171010_1007'),
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyphone',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='agencyemail',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Agency'),
        ),
        migrations.AddField(
            model_name='agencyemail',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.EmailAddress'),
        ),
        migrations.AddField(
            model_name='agencyaddress',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.Address'),
        ),
        migrations.AddField(
            model_name='agencyaddress',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Agency'),
        ),
        migrations.AddField(
            model_name='agency',
            name='addresses',
            field=models.ManyToManyField(related_name='agencies', through='agency.AgencyAddress', to='communication.Address'),
        ),
        migrations.AddField(
            model_name='agency',
            name='emails',
            field=models.ManyToManyField(related_name='agencies', through='agency.AgencyEmail', to='communication.EmailAddress'),
        ),
        migrations.AddField(
            model_name='agency',
            name='phones',
            field=models.ManyToManyField(related_name='agencies', through='agency.AgencyPhone', to='communication.PhoneNumber'),
        ),
    ]
