# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_agency_portal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyRequestForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('form', models.FileField(max_length=255, upload_to=b'agency_forms/%Y/%m/%d')),
                ('datetime_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
