# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_create_default_agency_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='can_email_appeals',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='contact_first_name',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='contact_last_name',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='contact_salutation',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='contact_title',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='other_emails',
        ),
    ]
