# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0014_agencyrequestform'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyRequestFormMapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappers', to='agency.AgencyRequestForm')),
            ],
        ),
        migrations.AddField(
            model_name='agency',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies', to='agency.AgencyRequestForm'),
        ),
    ]
