# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_agency_manual_stale'),
        ('agency', '0014_auto_20160713_1837'),
    ]

    operations = [
    ]
