# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0015_auto_20171205_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyrequestformmapper',
            name='value',
            field=models.CharField(choices=[(b'_agency_address', b'Agency address'), (b'_agency_name', b'Agency name'), (b'_date', b"Today's date"), (b'_email', b"This request's email address"), (b'_is_email', b'Are we emailing this request?'), (b'_is_fax', b'Are we faxing this request?'), (b'_is_snail', b'Are we snail mailing this request?'), (b'_phone', b"MuckRock's phone number"), (b'_requester_name', b"User's full name"), (b'_return_address_1', b'The street portion of the return address'), (b'_return_address_2', b'City/State/Zip of the return address')], max_length=255),
        ),
    ]
