# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 14:52

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0015_auto_20171205_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyrequestformmapper',
            name='value',
            field=models.CharField(
                choices=[('_agency_address',
                          'Agency address'), ('_agency_name', 'Agency name'),
                         ('_date', "Today's date"),
                         ('_email', "This request's email address"),
                         ('_is_email', 'Are we emailing this request?'),
                         ('_is_fax', 'Are we faxing this request?'),
                         ('_is_snail', 'Are we snail mailing this request?'),
                         ('_phone', "MuckRock's phone number"),
                         ('_requester_name', "User's full name"), (
                             '_return_address_1',
                             'The street portion of the return address'
                         ), (
                             '_return_address_2',
                             'City/State/Zip of the return address'
                         )],
                max_length=255
            ),
        ),
    ]
