# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-09 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0016_auto_20180208_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='address',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='can_email_appeals',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='email',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='other_emails',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='phone',
        ),
    ]
