# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-13 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0017_auto_20180409_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='exempt_note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
