# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-23 14:30


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0020_auto_20180713_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='location',
        ),
    ]
