# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 14:37


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0022_auto_20190325_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='uncooperative',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agencyaddress',
            name='request_type',
            field=models.CharField(choices=[(b'primary', b'Primary'), (b'appeal', b'Appeal'), (b'check', b'Check'), (b'none', b'None')], default=b'none', max_length=7),
        ),
    ]
