# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0023_auto_20190621_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='exempt',
            field=models.BooleanField(default=False, help_text=b'Mark agencies as exempt from public record laws.  Use the exempt note for further explanation'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='uncooperative',
            field=models.BooleanField(default=False, help_text=b'Mark agencies as unwilling to process our requests.  Use the exempt note for further explanation', verbose_name=b'Scowfflaw'),
        ),
    ]
