# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-01 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0025_remove_agency_payable_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'permissions': (('view_emails', 'Can view private contact information'), ('merge_agency', 'Can merge two agencies together'), ('mass_import', 'Can mass import a CSV of agencies')), 'verbose_name_plural': 'agencies'},
        ),
    ]
