# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-07 18:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0025_remove_agency_payable_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='appeal_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appeal_for', to='agency.Agency'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='jurisdiction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agencies', to='jurisdiction.Jurisdiction'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='agency.Agency'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies', to='portal.Portal'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who submitted this agency', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
