# Generated by Django 2.2.15 on 2021-04-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0029_auto_20201016_1327'),
        ('agency', '0026_auto_20200701_1115'),
    ]

    operations = [
    ]
