# Generated by Django 3.2.9 on 2023-01-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0030_merge_20210427_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='has_appeal',
            field=models.BooleanField(default=True),
        ),
    ]
