# Generated by Django 3.2.9 on 2023-01-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0031_agency_has_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='use_portal_appeal',
            field=models.BooleanField(default=False, help_text='Use the portal for appeals'),
        ),
    ]
