# Generated by Django 4.2 on 2023-05-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0032_agency_use_portal_appeal"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="last_log_update",
            field=models.DateField(blank=True, null=True),
        ),
    ]
