# Generated by Django 4.2 on 2024-03-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0033_agency_last_log_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="portal_payment_url",
            field=models.URLField(blank=True, verbose_name="Portal Payment URL"),
        ),
    ]
