# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_agency_requires_proxy'),
        ('accounts', '0015_auto_20160208_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('fax', models.CharField(blank=True, max_length=30)),
                ('salutation', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('contact_type', models.CharField(choices=[(b'primary', b'Primary'), (b'copy', b'Copy'), (b'appeal', b'Appeal'), (b'other', b'Other')], default=b'other', max_length=7)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='agency.Agency')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='acct_type',
            field=models.CharField(choices=[(b'admin', b'Admin'), (b'basic', b'Basic'), (b'beta', b'Beta'), (b'pro', b'Professional'), (b'proxy', b'Proxy'), (b'robot', b'Robot'), (b'agency', b'Agency')], max_length=10),
        ),
    ]
