# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20160208_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='total_agencies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_requests',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_requests_denied',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_requests_success',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_users',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
