# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20160208_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fax',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='salutation',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='acct_type',
            field=models.CharField(choices=[(b'admin', b'Admin'), (b'basic', b'Basic'), (b'beta', b'Beta'), (b'pro', b'Professional'), (b'proxy', b'Proxy'), (b'robot', b'Robot'), (b'agency', b'Agency'), (b'unknown', b'Unknown')], max_length=10),
        ),
    ]
