# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_agencyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
