# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-11 09:13
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_new_question_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=b'account_images'),
        ),
    ]
