# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_new_question_notifications'),
        ('accounts', '0018_auto_20160608_2034'),
    ]

    operations = [
    ]
