# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-14 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20161211_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_proxy',
            field=models.BooleanField(default=False, help_text=b'This user will be used over other proxies in the same state.  The account must still be set to type proxy for this to take affect'),
        ),
    ]
