# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-21 21:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0021_auto_20161228_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
