# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-23 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_receiptemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='org_share',
            field=models.BooleanField(default=False, help_text=b'Let other members of my organization view my embargoed requests'),
        ),
    ]
