# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-25 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_profile_org_share'),
        ('accounts', '0023_profile_source'),
    ]

    operations = [
    ]
