# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-23 21:26
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields
import muckrock.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20170327_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, storage=muckrock.core.storage.QueuedS3DietStorage(), upload_to=b'account_images'),
        ),
    ]
