# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-05 21:34
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20170525_2207'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE accounts_profile ALTER date_update SET NOT NULL', 
            'ALTER TABLE accounts_profile ALTER date_update DROP NOT NULL', 
        ),
        migrations.RunSQL(
            'ALTER TABLE accounts_profile ALTER monthly_requests SET NOT NULL', 
            'ALTER TABLE accounts_profile ALTER monthly_requests DROP NOT NULL', 
        ),
    ]
