# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 15:51
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20170820_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='total_reviewagency_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_unresolved_reviewagency_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
