# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 17:13
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20171025_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='portal_agencies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='sent_communications_portal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_portal_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_unresolved_portal_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
