# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 10:30
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20171123_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='total_deferred_crowdfundpayment_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_deferred_faxfail_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_deferred_flagged_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_deferred_generic_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_deferred_newagency_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_deferred_orphan_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_deferred_payment_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_deferred_portal_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_deferred_rejected_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_deferred_response_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_deferred_reviewagency_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_deferred_snailmail_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_deferred_staleagency_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_deferred_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
