# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 11:55
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20171215_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='num_crowdsource_responded_users',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_close_crowdsources',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_crowdsource_responses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_crowdsources',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_draft_crowdsources',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_open_crowdsources',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=b'account_images'),
        ),
    ]
