# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20180130_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_failed',
            field=models.BooleanField(default=False),
        ),
    ]
