# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-02 18:49

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_profile_email_failed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='num_crowdsource_responded_users',
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name='num assignment responded users'
            ),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_close_crowdsources',
            field=models.IntegerField(
                blank=True, null=True, verbose_name='total close assignments'
            ),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_crowdsource_responses',
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name='total assignment responses'
            ),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_crowdsources',
            field=models.IntegerField(
                blank=True, null=True, verbose_name='total assignments'
            ),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_draft_crowdsources',
            field=models.IntegerField(
                blank=True, null=True, verbose_name='total draft assignments'
            ),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_open_crowdsources',
            field=models.IntegerField(
                blank=True, null=True, verbose_name='total open assignments'
            ),
        ),
    ]
