# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-18 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20180402_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='total_composers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_composers_draft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_composers_filed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_composers_submitted',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
