# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-03 13:15


# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_profile_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='confirmation_key',
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
