# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-03 15:48


# Django
from django.db import migrations

# Standard Library
import uuid


def make_full_name(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    for profile in Profile.objects.all():
        profile.full_name = '{} {}'.format(
            profile.user.first_name,
            profile.user.last_name,
        ).strip()
        profile.save(update_fields=['full_name'])


def create_uuid(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    for profile in Profile.objects.all():
        profile.uuid = uuid.uuid4()
        profile.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20180803_0915'),
    ]

    operations = [
        migrations.RunPython(
            make_full_name, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            create_uuid, reverse_code=migrations.RunPython.noop
        ),
    ]
