# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-03 17:11


# Django
from django.db import migrations, models

# Standard Library
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20180803_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
