# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-16 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20181016_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='organization',
            new_name='_organization',
        ),
    ]
