# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-17 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20181016_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
