# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-11 15:03


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20181017_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='acct_type',
            field=models.CharField(choices=[(b'admin', b'Admin'), (b'basic', b'Basic'), (b'beta', b'Beta'), (b'pro', b'Professional'), (b'proxy', b'Proxy'), (b'robot', b'Robot'), (b'agency', b'Agency')], default=b'basic', max_length=10),
        ),
    ]
