# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-11 15:03

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20181017_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='acct_type',
            field=models.CharField(
                choices=[('admin', 'Admin'), ('basic', 'Basic'),
                         ('beta', 'Beta'), ('pro', 'Professional'),
                         ('proxy', 'Proxy'), ('robot',
                                              'Robot'), ('agency', 'Agency')],
                default='basic',
                max_length=10
            ),
        ),
    ]
