# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-21 21:44


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20181211_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='daily_requests_other',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
