# Generated by Django 2.2.15 on 2020-08-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_auto_20200804_1309'),
        ('organization', '0019_auto_20190107_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='_organization',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='acct_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='monthly_requests',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='num_requests',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='payment_failed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_id',
        ),
        migrations.DeleteModel(
            name='ReceiptEmail',
        ),
    ]
