# Generated by Django 3.2.9 on 2022-09-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_auto_20210325_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='email_communications_weekly_confirmed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='email_communications_weekly_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='fax_communications_weekly_confirmed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='fax_communications_weekly_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='mail_communications_weekly_confirmed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='mail_communications_weekly_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
