# Generated by Django 3.2.9 on 2022-09-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_auto_20220907_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='email_communications_weekly2_confirmed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='email_communications_weekly2_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='fax_communications_weekly2_confirmed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='fax_communications_weekly2_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='mail_communications_weekly2_confirmed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='mail_communications_weekly2_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
