# Generated by Django 4.2 on 2024-01-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0061_alter_stockresponse_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockresponse",
            name="type",
            field=models.CharField(
                choices=[
                    ("user", "Contact User"),
                    ("note", "Note"),
                    ("multi", "Multirequest Rejection"),
                    ("follow", "Follow Up"),
                ],
                default="user",
                max_length=6,
            ),
        ),
    ]
