# Generated by Django 4.2 on 2025-03-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0062_alter_stockresponse_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="statistics",
            name="machine_requests_consolidated",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="statistics",
            name="total_requests_consolidated",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockresponse",
            name="type",
            field=models.CharField(
                choices=[
                    ("user", "Contact User"),
                    ("note", "Note"),
                    ("multi", "Multirequest Rejection"),
                    ("follow", "Follow Up"),
                    ("agency", "New Agency Rejection"),
                ],
                default="user",
                max_length=6,
            ),
        ),
    ]
