# Generated by Django 4.2 on 2025-08-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0063_statistics_machine_requests_consolidated_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecurringDonation",
        ),
    ]
