# Generated by Django 4.2 on 2025-08-26 17:45

# Django
from django.contrib.auth.hashers import make_password
from django.db import migrations


def set_unusable_passwords(apps, schema_editor):
    User = apps.get_model("auth", "User")
    for user in User.objects.filter(password=""):
        user.password = make_password(None)
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0063_statistics_machine_requests_consolidated_and_more"),
    ]

    operations = [
        migrations.RunPython(
            set_unusable_passwords, reverse_code=migrations.RunPython.noop
        ),
    ]
