# Generated by Django 5.2.12 on 2026-07-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0065_internalnote"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="internalnote",
            name="warning_level",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "None"),
                    ("first", "First warning"),
                    ("second", "Second warning"),
                    ("final", "Final warning"),
                    ("banned", "Banned"),
                ],
            ),
        ),
    ]
