# Generated by Django 5.2.12 on 2026-07-23 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0066_notecategory_internalnote_warning_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalnote",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.NoteCategory",
            ),
        ),
    ]
