# Generated by Django 5.2.12 on 2026-08-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0068_default_note_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notecategory",
            options={"ordering": ("name",), "verbose_name_plural": "Note categories"},
        ),
        migrations.AddField(
            model_name="profile",
            name="blocked_from_filing",
            field=models.BooleanField(
                default=False,
                help_text="Prevent this user from filing new requests.  They will still be able to view and track the requests they have already filed.",
                verbose_name="Block from filing",
            ),
        ),
    ]
