# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foia', '0040_foiacommunication_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[(b'fbi', b'FBI eFOIPA Portal'), (b'foiaonline', b'FOIAonline'), (b'govqa', b'GovQA'), (b'nextrequest', b'NextRequest'), (b'other', b'Other')], max_length=11)),
                ('status', models.CharField(choices=[(b'good', b'Good'), (b'error', b'Error')], default=b'good', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PortalRequestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('foia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foia.FOIARequest')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Portal')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='portalrequestinfo',
            unique_together=set([('portal', 'foia')]),
        ),
    ]
