# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portalrequestinfo',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='portalrequestinfo',
            name='foia',
        ),
        migrations.RemoveField(
            model_name='portalrequestinfo',
            name='portal',
        ),
        migrations.DeleteModel(
            name='PortalRequestInfo',
        ),
    ]
