# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20171031_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal',
            name='type',
            field=models.CharField(choices=[(b'foiaonline', b'FOIAonline'), (b'govqa', b'GovQA'), (b'nextrequest', b'NextRequest'), (b'fbi', b'FBI eFOIPA Portal'), (b'other', b'Other')], max_length=11),
        ),
        migrations.AlterField(
            model_name='portal',
            name='url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
