# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 15:49

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_portal_created_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal',
            name='type',
            field=models.CharField(
                choices=[('foiaonline', 'FOIAonline'), ('govqa', 'GovQA'),
                         ('nextrequest',
                          'NextRequest'), ('foiaxpress', 'FOIAXpress'),
                         ('fbi', 'FBI eFOIPA Portal'), ('other', 'Other')],
                max_length=11
            ),
        ),
    ]
