# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-05 03:07

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20180517_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal',
            name='type',
            field=models.CharField(
                choices=[('foiaonline', 'FOIAonline'), ('govqa', 'GovQA'),
                         ('nextrequest',
                          'NextRequest'), ('foiaxpress', 'FOIAXpress'),
                         ('fbi', 'FBI eFOIPA Portal'), ('justfoia', 'JustFOIA'),
                         ('foiadirect',
                          'FOIA Direct'), ('webform',
                                           'Web Form'), ('other', 'Other')],
                max_length=11
            ),
        ),
    ]
