template: v1/cfn/shared/clusters/simple-ecs/image.template.yml
stack_name: muckrock-image
region: us-east-1
context:
  name: muckrock
  environment: image
  # Enable this to add support for quay.io legacy images
  # enable_legacy_quay_auth: true
  # Whether or not to allow public ssh to the cluster nodes.
  # internal_ssh_only: false
  # If true, this node will be in a public subnet and have a public IP assigned.
  # is_public: false
  # Enable to turn off datadog monitoring of instances
  # no_datadog: true
  # The root EBS volume.
  # root_volume:
  #   name: /dev/sda1
  #   size: 20 # size in Gb
  #   type: gp2
  # The default volume to store docker images and metadata.
  # docker_volume: # object, default is below.
  #   name: /dev/sdz
  #   size: 20 # size in Gb
  #   type: gp2
  # Additional EBS volumes to attach
  # volumes:
  #   -
  #     name: /dev/sdb # string, required. The mount point
  #     size: 20 # int, default. Size in gigabytes
  #     type: gp2 # string, default. Volume type.
  #     iops: 1000 # int, optional. Number of reserved IOPS to give volume.
  #     encrypted: false # boolean, default. whether or not to encrypt volume.
  #     snapshot_id: snap-abdc123 # string, optional. Snapshot from which to seed image
  #     instance_store: mnt # string, optional. If this option is selected, it negates all other options except name.  Requires the instance type to have instance store volumes.
