# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-27 21:29

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidebar', '0004_auto_20151222_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='context',
            field=models.CharField(
                choices=[('admin', 'Admin'), ('basic',
                                              'Basic'), ('beta', 'Beta'),
                         ('pro', 'Professional'), ('proxy',
                                                   'Proxy'), ('robot', 'Robot'),
                         ('agency', 'Agency'), ('anonymous', 'Visitor')],
                max_length=255,
                unique=True
            ),
        ),
    ]
