# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidebar', '0005_auto_20160331_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='context',
            field=models.CharField(choices=[(b'admin', b'Admin'), (b'basic', b'Basic'), (b'beta', b'Beta'), (b'pro', b'Professional'), (b'proxy', b'Proxy'), (b'robot', b'Robot'), (b'agency', b'Agency'), (b'unknown', b'Unknown'), (b'anonymous', b'Visitor')], max_length=255, unique=True),
        ),
    ]
