# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0007_auto_20150924_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiacommunication',
            name='autogenerated',
            field=models.BooleanField(default=False),
        ),
    ]
