# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0008_foiacommunication_autogenerated'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiarequest',
            name='date_processing',
            field=models.DateField(null=True, blank=True),
        ),
    ]
