# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0017_foiarequest_missing_proxy'),
        ('foia', '0017_remove_foiarequest_location'),
    ]

    operations = [
    ]
