# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 20:39

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0018_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foiarequest',
            name='missing_proxy',
            field=models.BooleanField(
                default=False,
                help_text=
                'This request requires a proxy to file, but no such proxy was avilable upon draft creation.'
            ),
        ),
    ]
