# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 21:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foia', '0019_auto_20160330_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiacommunication',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comms_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foiacommunication',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comms_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foiacommunication',
            name='delivered',
            field=models.CharField(blank=True, choices=[(b'fax', b'Fax'), (b'email', b'Email'), (b'mail', b'Mail'), (b'web', b'Web')], max_length=10, null=True),
        ),
    ]
