# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0019_auto_20160330_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foiarequest',
            options={'ordering': ['title'], 'permissions': (('view_foiarequest', 'Can view this request'), ('embargo_foiarequest', 'Can embargo request to make it private'), ('crowdfund_foiarequest', 'Can start a crowdfund campaign to pay for the request'), ('appeal_foiarequest', 'Can appeal the requests decision'), ('thank_foiarequest', 'Can thank the FOI officer for their help'), ('flag_foiarequest', 'Can flag the request for staff attention'), ('followup_foiarequest', 'Can send a manual follow up'), ('view_rawemail', 'Can view the raw email for communications'), ('file_multirequest', 'Can submit requests to multiple agencies')), 'verbose_name': 'FOIA Request'},
        ),
    ]
