# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0020_auto_20160419_2048'),
        ('foia', '0020_auto_20160331_2124'),
    ]

    operations = [
    ]
