# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-25 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0021_auto_20170124_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationerror',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='communicationopen',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='communicationopen',
            name='ip',
        ),
        migrations.AddField(
            model_name='communicationopen',
            name='ip_address',
            field=models.CharField(default='', max_length=15, verbose_name=b'IP Address'),
            preserve_default=False,
        ),
    ]
