# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 22:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foia', '0021_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foiarequest',
            options={'ordering': ['title'], 'permissions': (('view_foiarequest', 'Can view this request'), ('embargo_foiarequest', 'Can embargo request to make it private'), ('embargo_perm_foiarequest', 'Can embargo a request permananently'), ('crowdfund_foiarequest', 'Can start a crowdfund campaign for the request'), ('appeal_foiarequest', 'Can appeal the requests decision'), ('thank_foiarequest', 'Can thank the FOI officer for their help'), ('flag_foiarequest', 'Can flag the request for staff attention'), ('followup_foiarequest', 'Can send a manual follow up'), ('view_rawemail', 'Can view the raw email for communications'), ('file_multirequest', 'Can submit requests to multiple agencies')), 'verbose_name': 'FOIA Request'},
        ),
        migrations.AddField(
            model_name='foiarequest',
            name='cc_contacts',
            field=models.ManyToManyField(blank=True, null=True, related_name='_foiarequest_cc_contacts_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foiarequest',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
