# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_agencyuser'),
        ('foia', '0022_auto_20160510_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foiacommunication',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='foiarequest',
            name='contact',
        ),
        migrations.AddField(
            model_name='foiacommunication',
            name='to_users',
            field=models.ManyToManyField(related_name='comms_to', to='accounts.AgencyUser'),
        ),
        migrations.AddField(
            model_name='foiarequest',
            name='contacts',
            field=models.ManyToManyField(related_name='_foiarequest_contacts_+', to='accounts.AgencyUser'),
        ),
        migrations.AlterField(
            model_name='foiacommunication',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comms_from', to='accounts.AgencyUser'),
        ),
        migrations.AlterField(
            model_name='foiarequest',
            name='cc_contacts',
            field=models.ManyToManyField(related_name='_foiarequest_cc_contacts_+', to='accounts.AgencyUser'),
        ),
    ]
