# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-01 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0020_auto_20160419_2048'),
        ('foia', '0023_auto_20170212_1723'),
    ]

    operations = [
    ]
