# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 10:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0023_auto_20160522_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foiacommunication',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comms_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foiacommunication',
            name='to_users',
            field=models.ManyToManyField(related_name='comms_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
