# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 20:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foia', '0024_auto_20160522_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiacommunication',
            name='cc_users',
            field=models.ManyToManyField(related_name='comms_cc', to=settings.AUTH_USER_MODEL),
        ),
    ]
