# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-23 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0026_auto_20170320_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationopen',
            name='client_name',
            field=models.CharField(max_length=50),
        ),
    ]
