# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-27 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0027_auto_20170323_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiacommunication',
            name='fax_id',
            field=models.CharField(blank=True, default=b'', max_length=10),
        ),
    ]
