# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-19 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0029_outboundattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundattachment',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
