# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-26 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0032_auto_20170423_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foiacommunication',
            name='status',
            field=models.CharField(blank=True, choices=[(b'started', b'Draft'), (b'submitted', b'Processing'), (b'ack', b'Awaiting Acknowledgement'), (b'processed', b'Awaiting Response'), (b'appealing', b'Awaiting Appeal'), (b'fix', b'Fix Required'), (b'payment', b'Payment Required'), (b'lawsuit', b'In Litigation'), (b'rejected', b'Rejected'), (b'no_docs', b'No Responsive Documents'), (b'done', b'Completed'), (b'partial', b'Partially Completed'), (b'abandoned', b'Withdrawn')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='foiarequest',
            name='status',
            field=models.CharField(choices=[(b'started', b'Draft'), (b'submitted', b'Processing'), (b'ack', b'Awaiting Acknowledgement'), (b'processed', b'Awaiting Response'), (b'appealing', b'Awaiting Appeal'), (b'fix', b'Fix Required'), (b'payment', b'Payment Required'), (b'lawsuit', b'In Litigation'), (b'rejected', b'Rejected'), (b'no_docs', b'No Responsive Documents'), (b'done', b'Completed'), (b'partial', b'Partially Completed'), (b'abandoned', b'Withdrawn')], db_index=True, max_length=10),
        ),
    ]
