# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-26 22:02

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0032_auto_20170423_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foiacommunication',
            name='status',
            field=models.CharField(
                blank=True,
                choices=[('started', 'Draft'), ('submitted', 'Processing'),
                         ('ack', 'Awaiting Acknowledgement'),
                         ('processed', 'Awaiting Response'),
                         ('appealing',
                          'Awaiting Appeal'), ('fix', 'Fix Required'),
                         ('payment', 'Payment Required'),
                         ('lawsuit', 'In Litigation'), ('rejected', 'Rejected'),
                         ('no_docs',
                          'No Responsive Documents'), ('done', 'Completed'),
                         ('partial',
                          'Partially Completed'), ('abandoned', 'Withdrawn')],
                max_length=10,
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='foiarequest',
            name='status',
            field=models.CharField(
                choices=[('started', 'Draft'), ('submitted', 'Processing'),
                         ('ack', 'Awaiting Acknowledgement'),
                         ('processed', 'Awaiting Response'),
                         ('appealing',
                          'Awaiting Appeal'), ('fix', 'Fix Required'),
                         ('payment', 'Payment Required'),
                         ('lawsuit', 'In Litigation'), ('rejected', 'Rejected'),
                         ('no_docs',
                          'No Responsive Documents'), ('done', 'Completed'),
                         ('partial',
                          'Partially Completed'), ('abandoned', 'Withdrawn')],
                db_index=True,
                max_length=10
            ),
        ),
    ]
