# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-27 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0033_auto_20170605_2222'),
        ('foia', '0033_auto_20170626_2202'),
    ]

    operations = [
    ]
