# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0035_auto_20170927_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiarequest',
            name='multirequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foia.FOIAMultiRequest'),
        ),
        migrations.AlterField(
            model_name='foiamultirequest',
            name='num_monthly_requests',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='foiamultirequest',
            name='num_org_requests',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='foiamultirequest',
            name='num_reg_requests',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
