# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0038_auto_20171004_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foiacommunication',
            name='from_who',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
