# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0041_foiarequest_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiarequest',
            name='portal_password',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
