# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-07 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0044_auto_20180207_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foiafile',
            name='access',
            field=models.CharField(choices=[(b'public', b'Public'), (b'private', b'Private'), (b'organization', b'Organization')], db_index=True, default=b'public', max_length=12),
        ),
    ]
