# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-07 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0045_auto_20180206_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingnumber',
            name='tracking_id',
            field=models.CharField(max_length=255, verbose_name=b'Tracking Number'),
        ),
    ]
