# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0046_auto_20180207_1126'),
        ('foia', '0045_auto_20180207_1616'),
    ]

    operations = [
    ]
