# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0047_merge_20180208_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foiarequest',
            name='tracking_id',
        ),
    ]
