# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 11:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20180122_1353'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jurisdiction', '0013_jurisdiction_aliases'),
        ('agency', '0016_auto_20180208_1452'),
        ('tags', '0002_remove_tag_user'),
        ('foia', '0048_remove_foiarequest_tracking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FOIASavedSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('query', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[(b'', b'-'), (b'started', b'Draft'), (b'submitted', b'Processing'), (b'ack', b'Awaiting Acknowledgement'), (b'processed', b'Awaiting Response'), (b'appealing', b'Awaiting Appeal'), (b'fix', b'Fix Required'), (b'payment', b'Payment Required'), (b'lawsuit', b'In Litigation'), (b'rejected', b'Rejected'), (b'no_docs', b'No Responsive Documents'), (b'done', b'Completed'), (b'partial', b'Partially Completed'), (b'abandoned', b'Withdrawn')], max_length=10)),
                ('embargo', models.NullBooleanField()),
                ('exclude_crowdfund', models.NullBooleanField()),
                ('min_pages', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_date', models.DateField(blank=True, null=True)),
                ('max_date', models.DateField(blank=True, null=True)),
                ('agencies', models.ManyToManyField(to='agency.Agency')),
            ],
        ),
        migrations.CreateModel(
            name='SearchJurisdiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_local', models.BooleanField()),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jurisdiction.Jurisdiction')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foia.FOIASavedSearch')),
            ],
        ),
        migrations.AddField(
            model_name='foiasavedsearch',
            name='jurisdictions',
            field=models.ManyToManyField(through='foia.SearchJurisdiction', to='jurisdiction.Jurisdiction'),
        ),
        migrations.AddField(
            model_name='foiasavedsearch',
            name='projects',
            field=models.ManyToManyField(to='project.Project'),
        ),
        migrations.AddField(
            model_name='foiasavedsearch',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
        migrations.AddField(
            model_name='foiasavedsearch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foiasavedsearch',
            name='users',
            field=models.ManyToManyField(related_name='_foiasavedsearch_users_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='foiasavedsearch',
            unique_together=set([('user', 'title')]),
        ),
    ]
