# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0049_auto_20180209_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiamultirequest',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foia.FOIAMultiRequest'),
        ),
    ]
