# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-20 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0051_auto_20180319_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiamultirequest',
            name='composer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi', to='foia.FOIAComposer'),
        ),
    ]
