# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-20 12:42
from __future__ import unicode_literals

# Django
from django.db import migrations


def convert_composers(apps, schema_editor):
    FOIARequest = apps.get_model('foia', 'FOIARequest')
    FOIAMultiRequest = apps.get_model('foia', 'FOIAMultiRequest')
    FOIAComposer = apps.get_model('foia', 'FOIAComposer')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Tag = apps.get_model('tags', 'Tag')
    TaggedItemBase = apps.get_model('tags', 'TaggedItemBase')

    def convert_multi(multi):
        if multi.parent is not None and multi.parent.composer is None:
            convert_multi(multi.parent)
        composer = FOIAComposer.objects.create(
            user=multi.user,
            title=multi.title,
            slug=multi.slug,
            status=multi.status,
            requested_docs=multi.requested_docs,
            embargo=multi.embargo,
            parent=multi.parent.composer if multi.parent else None,
            num_org_requests=multi.num_org_requests,
            num_monthly_requests=multi.num_monthly_requests,
            num_reg_requests=multi.num_reg_requests,
        )
        composer.agencies.set(multi.agencies.all())
        ct_multi = ContentType.objects.get(model='foiamultirequest')
        ct_comp = ContentType.objects.get(model='foiacomposer')
        tags = Tag.objects.filter(
            tags_taggeditembase_items__content_type=ct_multi,
            tags_taggeditembase_items__object_id=multi.pk,
        )
        for tag in tags:
            TaggedItemBase.objects.create(
                tag=tag,
                content_type=ct_comp,
                object_id=composer.pk,
            )
        multi.composer = composer
        multi.save()
        if multi.foias.exist():
            composer.datetime_submitted = multi.foias.first().date_submitted
            composer.save()
            multi.foias.all().update(composer=composer)

    def convert_foia(foia):
        if foia.parent is not None and foia.parent.composer is None:
            convert_foia(foia.parent)
        composer = FOIAComposer.objects.create(
            user=foia.user,
            title=foia.title,
            slug=foia.slug,
            status='started' if foia.status == 'started' else 'filed',
            requested_docs=foia.requested_docs,
            datetime_submitted=foia.date_submitted,
            embargo=foia.embargo,
            parent=foia.parent.composer if foia.parent else None,
        )
        if foia.agency:
            composer.agencies.add(foia.agency)
        # do tags manually due to missing functionality in migrations #
        ct_foia = ContentType.objects.get(model='foiarequest')
        ct_comp = ContentType.objects.get(model='foiacomposer')
        tags = Tag.objects.filter(
            tags_taggeditembase_items__content_type=ct_foia,
            tags_taggeditembase_items__object_id=foia.pk,
        )
        for tag in tags:
            TaggedItemBase.objects.create(
                tag=tag,
                content_type=ct_comp,
                object_id=composer.pk,
            )
        # end tag code #
        if foia.status == 'started' and foia.communications.exist():
            composer.edited_boilerplate = True
            composer.requested_docs = foia.communications.first().communication
            composer.save()
            foia.delete()
        elif foia.status == 'started':
            foia.delete()
        else:
            foia.composer = composer
            foia.save()

    for multi in (
        FOIAMultiRequest.objects.all().select_related('parent__composer')
        .prefetch_related('agencies', 'foias')
    ):
        convert_multi(multi)
    for foia in (
        FOIARequest.objects.filter(composer=None).select_related(
            'parent__composer', 'agency'
        )
    ):
        convert_foia(foia)


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0052_foiamultirequest_composer'),
        ('tags', '0002_remove_tag_user'),
        ('contenttypes', '0001_initial'),
    ]

    operations = [migrations.RunPython(convert_composers)]
