# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-20 14:13

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0055_auto_20180323_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foiacomposer',
            options={
                'permissions': (('view_foiacomposer', 'Can view this composer'),
                                ),
                'verbose_name':
                    'FOIA Composer'
            },
        ),
        migrations.AlterField(
            model_name='foiacommunication',
            name='status',
            field=models.CharField(
                blank=True,
                choices=[('submitted',
                          'Processing'), ('ack', 'Awaiting Acknowledgement'),
                         ('processed', 'Awaiting Response'),
                         ('appealing',
                          'Awaiting Appeal'), ('fix', 'Fix Required'),
                         ('payment', 'Payment Required'),
                         ('lawsuit', 'In Litigation'), ('rejected', 'Rejected'),
                         ('no_docs',
                          'No Responsive Documents'), ('done', 'Completed'),
                         ('partial',
                          'Partially Completed'), ('abandoned', 'Withdrawn')],
                max_length=10,
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='foiarequest',
            name='status',
            field=models.CharField(
                choices=[('submitted',
                          'Processing'), ('ack', 'Awaiting Acknowledgement'),
                         ('processed', 'Awaiting Response'),
                         ('appealing',
                          'Awaiting Appeal'), ('fix', 'Fix Required'),
                         ('payment', 'Payment Required'),
                         ('lawsuit', 'In Litigation'), ('rejected', 'Rejected'),
                         ('no_docs',
                          'No Responsive Documents'), ('done', 'Completed'),
                         ('partial',
                          'Partially Completed'), ('abandoned', 'Withdrawn')],
                db_index=True,
                max_length=10
            ),
        ),
        migrations.AlterField(
            model_name='foiasavedsearch',
            name='status',
            field=models.CharField(
                choices=[
                    ('',
                     '-'), ('submitted',
                            'Processing'), ('ack', 'Awaiting Acknowledgement'),
                    ('processed',
                     'Awaiting Response'), ('appealing', 'Awaiting Appeal'),
                    ('fix', 'Fix Required'), ('payment', 'Payment Required'),
                    ('lawsuit', 'In Litigation'), ('rejected', 'Rejected'),
                    ('no_docs',
                     'No Responsive Documents'), ('done', 'Completed'),
                    ('partial',
                     'Partially Completed'), ('abandoned', 'Withdrawn')
                ],
                max_length=10
            ),
        ),
    ]
