# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 18:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import muckrock.foia.models.attachment


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foia', '0055_auto_20180323_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundComposerAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ffile', models.FileField(max_length=255, upload_to=muckrock.foia.models.attachment.attachment_path, verbose_name=b'file')),
                ('date_time_stamp', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='foiacomposer',
            options={'permissions': (('view_foiacomposer', 'Can view this composer'),), 'verbose_name': 'FOIA Composer'},
        ),
        migrations.AlterField(
            model_name='outboundattachment',
            name='ffile',
            field=models.FileField(max_length=255, upload_to=muckrock.foia.models.attachment.attachment_path, verbose_name=b'file'),
        ),
        migrations.AlterField(
            model_name='outboundattachment',
            name='foia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_request_attachments', to='foia.FOIARequest'),
        ),
        migrations.AlterField(
            model_name='outboundattachment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_outboundattachment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outboundcomposerattachment',
            name='composer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_composer_attachments', to='foia.FOIAComposer'),
        ),
        migrations.AddField(
            model_name='outboundcomposerattachment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_outboundcomposerattachment', to=settings.AUTH_USER_MODEL),
        ),
    ]
