# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-20 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0055_auto_20180323_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foiacomposer',
            options={'permissions': (('view_foiacomposer', 'Can view this composer'),), 'verbose_name': 'FOIA Composer'},
        ),
        migrations.AlterField(
            model_name='foiacommunication',
            name='status',
            field=models.CharField(blank=True, choices=[(b'submitted', b'Processing'), (b'ack', b'Awaiting Acknowledgement'), (b'processed', b'Awaiting Response'), (b'appealing', b'Awaiting Appeal'), (b'fix', b'Fix Required'), (b'payment', b'Payment Required'), (b'lawsuit', b'In Litigation'), (b'rejected', b'Rejected'), (b'no_docs', b'No Responsive Documents'), (b'done', b'Completed'), (b'partial', b'Partially Completed'), (b'abandoned', b'Withdrawn')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='foiarequest',
            name='status',
            field=models.CharField(choices=[(b'submitted', b'Processing'), (b'ack', b'Awaiting Acknowledgement'), (b'processed', b'Awaiting Response'), (b'appealing', b'Awaiting Appeal'), (b'fix', b'Fix Required'), (b'payment', b'Payment Required'), (b'lawsuit', b'In Litigation'), (b'rejected', b'Rejected'), (b'no_docs', b'No Responsive Documents'), (b'done', b'Completed'), (b'partial', b'Partially Completed'), (b'abandoned', b'Withdrawn')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='foiasavedsearch',
            name='status',
            field=models.CharField(choices=[(b'', b'-'), (b'submitted', b'Processing'), (b'ack', b'Awaiting Acknowledgement'), (b'processed', b'Awaiting Response'), (b'appealing', b'Awaiting Appeal'), (b'fix', b'Fix Required'), (b'payment', b'Payment Required'), (b'lawsuit', b'In Litigation'), (b'rejected', b'Rejected'), (b'no_docs', b'No Responsive Documents'), (b'done', b'Completed'), (b'partial', b'Partially Completed'), (b'abandoned', b'Withdrawn')], max_length=10),
        ),
    ]
