# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 18:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import muckrock.foia.models.attachment


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foia', '0056_auto_20180326_1409'),
    ]

    operations = [
        migrations.RenameModel('OutboundAttachment', 'OutboundRequestAttachment'),
    ]
