# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-20 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0056_auto_20180420_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foiacommunication',
            options={'ordering': ['datetime'], 'verbose_name': 'FOIA Communication'},
        ),
        migrations.RenameField(
            model_name='foiacommunication',
            old_name='date',
            new_name='datetime',
        ),
    ]
