# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-20 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0057_auto_20180420_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foiafile',
            options={'ordering': ['datetime'], 'verbose_name': 'FOIA Document File'},
        ),
        migrations.RenameField(
            model_name='foiafile',
            old_name='date',
            new_name='datetime',
        ),
    ]
