# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 18:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0057_auto_20180326_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundrequestattachment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_outboundrequestattachment', to=settings.AUTH_USER_MODEL),
        ),
    ]
