# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0058_auto_20180326_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundcomposerattachment',
            name='composer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_attachments', to='foia.FOIAComposer'),
        ),
        migrations.AlterField(
            model_name='outboundrequestattachment',
            name='foia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_attachments', to='foia.FOIARequest'),
        ),
    ]
