# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-13 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0059_auto_20180426_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foiarequest',
            options={'ordering': ['title'], 'permissions': (('view_foiarequest', 'Can view this request'), ('embargo_foiarequest', 'Can embargo request to make it private'), ('embargo_perm_foiarequest', 'Can embargo a request permananently'), ('crowdfund_foiarequest', 'Can start a crowdfund campaign for the request'), ('appeal_foiarequest', 'Can appeal the requests decision'), ('thank_foiarequest', 'Can thank the FOI officer for their help'), ('flag_foiarequest', 'Can flag the request for staff attention'), ('followup_foiarequest', 'Can send a manual follow up'), ('agency_reply_foiarequest', 'Can send a direct reply'), ('upload_attachment_foiarequest', 'Can upload an attachment'), ('pay_foiarequest', 'Can pay for a request'), ('export_csv', 'Can export a CSV of search results'), ('zip_download_foiarequest', 'Can download a zip file of all communications and files')), 'verbose_name': 'FOIA Request'},
        ),
        migrations.AlterField(
            model_name='foiacomposer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foiarequest',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foias', to='communication.Address'),
        ),
        migrations.AlterField(
            model_name='foiarequest',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agency.Agency'),
        ),
        migrations.AlterField(
            model_name='foiarequest',
            name='composer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foias', to='foia.FOIAComposer'),
        ),
        migrations.AlterField(
            model_name='foiarequest',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foias', to='communication.EmailAddress'),
        ),
        migrations.AlterField(
            model_name='foiarequest',
            name='fax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foias', to='communication.PhoneNumber'),
        ),
        migrations.AlterField(
            model_name='foiarequest',
            name='portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foias', to='portal.Portal'),
        ),
    ]
