# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-13 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0059_auto_20180327_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiacomposer',
            name='delayed_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='foiacomposer',
            name='datetime_created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='foiarequest',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foias', to='agency.Agency'),
        ),
    ]
