# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-12 21:23


from django.db import migrations, models
import muckrock.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0061_foiarequest_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foiarequest',
            name='portal_password',
            field=models.CharField(blank=True, default=muckrock.core.utils.generate_key, max_length=20),
        ),
    ]
