# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-11 15:00


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0062_auto_20181112_1623'),
        ('foia', '0062_foiacomposer_organization'),
    ]

    operations = [
    ]
