# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-25 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0062_auto_20181112_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foiarequest',
            options={'ordering': ['title'], 'permissions': (('view_foiarequest', 'Can view this request'), ('embargo_foiarequest', 'Can embargo request to make it private'), ('embargo_perm_foiarequest', 'Can embargo a request permananently'), ('crowdfund_foiarequest', 'Can start a crowdfund campaign for the request'), ('appeal_foiarequest', 'Can appeal the requests decision'), ('thank_foiarequest', 'Can thank the FOI officer for their help'), ('flag_foiarequest', 'Can flag the request for staff attention'), ('followup_foiarequest', 'Can send a manual follow up'), ('agency_reply_foiarequest', 'Can send a direct reply'), ('upload_attachment_foiarequest', 'Can upload an attachment'), ('pay_foiarequest', 'Can pay for a request'), ('export_csv', 'Can export a CSV of search results'), ('set_info_foiarequest', 'Can send communications to custom addresses'), ('zip_download_foiarequest', 'Can download a zip file of all communications and files')), 'verbose_name': 'FOIA Request'},
        ),
        migrations.AlterField(
            model_name='foiamultirequest',
            name='agencies',
            field=models.ManyToManyField(blank=True, related_name='multirequests', to='agency.Agency'),
        ),
    ]
