# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-27 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0065_auto_20190227_1250'),
        ('foia', '0063_auto_20190325_1004'),
    ]

    operations = [
    ]
