# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-18 18:24

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0068_foiarequest_noindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foiarequest',
            name='noindex',
            field=models.BooleanField(
                default=False,
                help_text=
                "This request's page should not be indexed by search engines",
                verbose_name='No Index'
            ),
        ),
    ]
