# Generated by Django 2.2.15 on 2020-08-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0072_auto_20200804_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foiacomposer',
            name='num_org_requests',
        ),
    ]
