# Generated by Django 2.2.15 on 2020-09-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0073_remove_foiacomposer_num_org_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foiacommunication',
            name='subject',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
