# Generated by Django 2.2.15 on 2020-08-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0073_remove_foiacomposer_num_org_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiafile',
            name='dc_legacy',
            field=models.BooleanField(default=True),
        ),
    ]
