# Generated by Django 2.2.15 on 2020-09-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0075_auto_20200828_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foiafile',
            name='access',
            field=models.CharField(db_column='access', db_index=True, default='public', max_length=12),
        ),
    ]
