# Generated by Django 2.2.15 on 2020-09-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0077_auto_20200911_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foiacommunication',
            name='subject',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
