# Generated by Django 2.2.15 on 2020-12-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0077_auto_20200911_0945'),
        ('foia', '0074_auto_20200924_1225'),
    ]

    operations = [
    ]
