# Generated by Django 2.2.15 on 2020-12-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0078_merge_20201203_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foiafile',
            name='doc_id',
            field=models.SlugField(blank=True, editable=False, max_length=266),
        ),
    ]
