# Generated by Django 2.2.15 on 2021-01-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0079_auto_20201210_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foiafile',
            name='dc_legacy',
        ),
        migrations.RemoveField(
            model_name='foiafile',
            name='old_access',
        ),
    ]
