# Generated by Django 2.2.15 on 2021-01-28 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0078_merge_20201001_1138'),
        ('foia', '0079_auto_20201210_1302'),
    ]

    operations = [
    ]
