# Generated by Django 2.2.15 on 2021-02-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0080_auto_20210129_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiarequest',
            name='passcode',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
