# Generated by Django 2.2.15 on 2021-02-01 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0080_merge_20210128_1502'),
        ('foia', '0080_auto_20210129_1329'),
    ]

    operations = [
    ]
