# Generated by Django 2.2.15 on 2021-03-25 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foia', '0080_auto_20210129_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiarequest',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proxy_foias', to=settings.AUTH_USER_MODEL),
        ),
    ]
