# Generated by Django 2.2.15 on 2021-04-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0081_foiarequest_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foiarequest',
            name='title',
            field=models.CharField(db_index=True, max_length=1024),
        ),
    ]
