# Generated by Django 2.2.15 on 2021-03-31 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0081_foiarequest_passcode'),
        ('foia', '0081_foiarequest_proxy'),
    ]

    operations = [
    ]
