# Generated by Django 2.2.15 on 2021-04-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0082_auto_20210422_1145'),
        ('foia', '0082_merge_20210331_1625'),
    ]

    operations = [
    ]
