# Generated by Django 2.2.15 on 2021-05-13 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0024_jurisdiction_always_proxy'),
        ('foia', '0084_foiatemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiatemplate',
            name='jurisdiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='jurisdiction.Jurisdiction'),
        ),
    ]
