# Generated by Django 2.2.15 on 2021-06-14 17:47

# Django
from django.db import migrations


def make_default_template(apps, schema_editor):
    FOIATemplate = apps.get_model("foia", "FOIATemplate")
    User = apps.get_model("auth", "User")
    try:
        user = User.objects.get(username="MuckrockStaff")
    except User.DoesNotExist:
        return

    FOIATemplate.objects.create(
        name="Default",
        user=user,
        template="To Whom It May Concern:\r\n\r\nPursuant to the { law name }, I hereby request the following records:\r\n\r\n{ requested docs }\r\n\r\n{ waiver }\r\n\r\nIn the event that there are fees, I would be grateful if you would inform me of the total charges in advance of fulfilling my request. I would prefer the request filled electronically, by e-mail attachment if available or CD-ROM if not.\r\n\r\nThank you in advance for your anticipated cooperation in this matter. I look forward to receiving your response to this request within { days }.\r\n\r\n{ closing }",
    )


def remove_default_template(apps, schema_editor):
    FOIATemplate = apps.get_model("foia", "FOIATemplate")
    FOIATemplate.objects.filter(name="Default").delete()


class Migration(migrations.Migration):

    dependencies = [("foia", "0086_auto_20210513_1631")]

    operations = [migrations.RunPython(make_default_template, remove_default_template)]
