# Generated by Django 2.2.15 on 2021-06-28 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0087_auto_20210614_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foiarequest',
            options={'ordering': ['title'], 'permissions': (('embargo_foiarequest', 'Can embargo request to make it private'), ('embargo_perm_foiarequest', 'Can embargo a request permananently'), ('crowdfund_foiarequest', 'Can start a crowdfund campaign for the request'), ('appeal_foiarequest', 'Can appeal the requests decision'), ('thank_foiarequest', 'Can thank the FOI officer for their help'), ('flag_foiarequest', 'Can flag the request for staff attention'), ('followup_foiarequest', 'Can send a manual follow up'), ('agency_reply_foiarequest', 'Can send a direct reply'), ('upload_attachment_foiarequest', 'Can upload an attachment'), ('pay_foiarequest', 'Can pay for a request'), ('export_csv', 'Can export a CSV of search results'), ('unlimited_attachment_size', 'Can upload attachments of any size'), ('set_info_foiarequest', 'Can send communications to custom addresses'), ('zip_download_foiarequest', 'Can download a zip file of all communications and files'), ('tasks_foiarequest', 'Can manage tasks associated with this request')), 'verbose_name': 'FOIA Request'},
        ),
    ]
