# Generated by Django 2.2.15 on 2021-09-09 15:05

from django.db import migrations, models
import muckrock.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0089_merge_20210719_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawemail',
            old_name='raw_email',
            new_name='raw_email_db',
        ),
        migrations.AddField(
            model_name='rawemail',
            name='raw_email_file',
            field=models.FileField(blank=True, storage=muckrock.core.storage.PrivateMediaRootS3BotoStorage, upload_to='raw_emails/%Y/%m/%d'),
        ),
    ]
