# Generated by Django 2.2.15 on 2021-09-13 20:20

from django.db import migrations, models
import muckrock.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0090_auto_20210909_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawemail',
            name='raw_email_file',
            field=models.FileField(blank=True, storage=muckrock.core.storage.PrivateMediaRootS3BotoStorage(), upload_to='raw_emails/%Y/%m/%d'),
        ),
    ]
