# Generated by Django 2.2.15 on 2021-10-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0091_auto_20210913_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiacommunication',
            name='download',
            field=models.BooleanField(default=False, help_text='This communication has pending files to download'),
        ),
    ]
