# Generated by Django 3.2.9 on 2021-12-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0092_foiacommunication_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foiasavedsearch',
            name='embargo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foiasavedsearch',
            name='exclude_crowdfund',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
