# Generated by Django 3.2.9 on 2022-08-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0093_auto_20211202_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiacommunication',
            name='category',
            field=models.CharField(blank=True, choices=[('a', 'Appeal'), ('n', 'New'), ('u', 'Update'), ('f', 'Followup'), ('p', 'Payment')], max_length=1),
        ),
    ]
