# Generated by Django 4.2 on 2023-07-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0095_foianote_notify_alter_foiasavedsearch_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foianote',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
