# Generated by Django 4.2 on 2023-05-02 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("foia", "0095_foialog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="foialog",
            old_name="date",
            new_name="date_requested",
        ),
        migrations.AddField(
            model_name="foialog",
            name="date_completed",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foialog",
            name="foia_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="foia.foiarequest",
            ),
        ),
        migrations.AddField(
            model_name="foialog",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("submitted", "Processing"),
                    ("ack", "Awaiting Acknowledgement"),
                    ("processed", "Awaiting Response"),
                    ("appealing", "Awaiting Appeal"),
                    ("fix", "Fix Required"),
                    ("payment", "Payment Required"),
                    ("lawsuit", "In Litigation"),
                    ("rejected", "Rejected"),
                    ("no_docs", "No Responsive Documents"),
                    ("done", "Completed"),
                    ("partial", "Partially Completed"),
                    ("abandoned", "Withdrawn"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="foiasavedsearch",
            name="users",
            field=models.ManyToManyField(related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="outboundcomposerattachment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pending_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="outboundrequestattachment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pending_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
