# Generated by Django 4.2 on 2023-06-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0095_foianote_notify_alter_foiasavedsearch_users_and_more"),
        ("foia", "0096_rename_date_foialog_date_requested_and_more"),
    ]

    operations = []
