# Generated by Django 4.2 on 2023-07-31 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0096_alter_foianote_notify"),
        ("foia", "0097_merge_20230628_1223"),
    ]

    operations = []
