# Generated by Django 4.2 on 2023-08-31 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0033_agency_last_log_update"),
        ("foia", "0097_merge_20230628_1223"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="foialog",
            options={"ordering": ["date_requested"], "verbose_name": "FOIA Log"},
        ),
        migrations.RenameField(
            model_name="foialog",
            old_name="requestor",
            new_name="requester",
        ),
        migrations.AddField(
            model_name="foialog",
            name="datetime_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="foialog",
            name="exemptions",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="foialog",
            name="requester_organization",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="foialog",
            name="source",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="foialog",
            name="date_requested",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="foialog",
            name="request_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="foianote",
            name="notify",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="foialog",
            unique_together={("request_id", "agency")},
        ),
    ]
