# Generated by Django 4.2 on 2023-08-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0098_alter_foialog_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foialog",
            name="requester",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
