# Generated by Django 4.2 on 2023-09-11 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0096_alter_foianote_notify"),
        ("foia", "0099_alter_foialog_requester"),
    ]

    operations = []
