# Generated by Django 4.2 on 2023-08-31 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0098_merge_20230731_1031"),
        ("foia", "0099_alter_foialog_requester"),
    ]

    operations = []
