# Generated by Django 4.2 on 2023-09-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0100_merge_20230831_1131"),
        ("foia", "0100_merge_20230911_1631"),
    ]

    operations = []
