# Generated by Django 4.2 on 2023-10-24 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agency", "0033_agency_last_log_update"),
        ("foia", "0101_auto_20231024_1643"),
    ]

    operations = [
        migrations.CreateModel(
            name="FOIALog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("internal_note", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="URL, MuckRock request, or wherever the log was obtained from",
                        max_length=255,
                    ),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="agency.agency"
                    ),
                ),
                (
                    "contributed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="foia_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FOIA Log",
            },
        ),
        migrations.CreateModel(
            name="FOIALogEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(max_length=255)),
                ("requester", models.CharField(blank=True, max_length=255)),
                (
                    "requester_organization",
                    models.CharField(blank=True, max_length=255),
                ),
                ("subject", models.TextField()),
                ("exemptions", models.CharField(blank=True, max_length=255)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("date_requested", models.DateField(blank=True, null=True)),
                ("date_completed", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("submitted", "Processing"),
                            ("ack", "Awaiting Acknowledgement"),
                            ("processed", "Awaiting Response"),
                            ("appealing", "Awaiting Appeal"),
                            ("fix", "Fix Required"),
                            ("payment", "Payment Required"),
                            ("lawsuit", "In Litigation"),
                            ("rejected", "Rejected"),
                            ("no_docs", "No Responsive Documents"),
                            ("done", "Completed"),
                            ("partial", "Partially Completed"),
                            ("abandoned", "Withdrawn"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "foia_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="foia.foialog"
                    ),
                ),
                (
                    "foia_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="foia.foiarequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "FOIA Log Entry",
                "ordering": ["date_requested"],
            },
        ),
    ]
