# Generated by Django 4.2 on 2024-04-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0103_remove_foialogentry_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foialogentry',
            options={'ordering': ['date_requested'], 'verbose_name': 'FOIA Log Entry', 'verbose_name_plural': 'FOIA Log Entries'},
        ),
    ]
