# Generated by Django 4.2 on 2023-10-27 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0101_merge_20230926_1304"),
        ("foia", "0103_remove_foialogentry_source"),
    ]

    operations = []
