# Generated by Django 4.2 on 2024-04-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0104_alter_foialogentry_options"),
        ("foia", "0104_merge_20231027_1000"),
    ]

    operations = []
