# Generated by Django 4.2 on 2024-06-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0105_foialogentry_request_url"),
        ("foia", "0105_merge_20240404_0956"),
    ]

    operations = []
