# Generated by Django 4.2 on 2024-09-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0105_foialogentry_request_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="foiacomposer",
            name="embargo_status",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("embargo", "Embargo"),
                    ("permanent", "Permanent Embargo"),
                ],
                default="public",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="foiarequest",
            name="embargo_status",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("embargo", "Embargo"),
                    ("permanent", "Permanent Embargo"),
                ],
                default="public",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="foiasavedsearch",
            name="embargo_status",
            field=models.CharField(
                choices=[
                    ("", "-"),
                    ("public", "Public"),
                    ("embargo", "Embargo"),
                    ("permanent", "Permanent Embargo"),
                ],
                default="",
                max_length=9,
            ),
        ),
    ]
