# Generated by Django 4.2 on 2024-09-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0107_auto_20240911_1428"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foiacomposer",
            name="embargo",
        ),
        migrations.RemoveField(
            model_name="foiacomposer",
            name="permanent_embargo",
        ),
        migrations.RemoveField(
            model_name="foiarequest",
            name="embargo",
        ),
        migrations.RemoveField(
            model_name="foiarequest",
            name="permanent_embargo",
        ),
        migrations.RemoveField(
            model_name="foiasavedsearch",
            name="embargo",
        ),
    ]
