# Generated by Django 4.2 on 2025-02-04 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0034_agency_portal_payment_url"),
        ("foia", "0108_remove_foiacomposer_embargo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="foiarequest",
            name="disable_gloo",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="foiacommunication",
            name="autogenerated",
            field=models.BooleanField(
                default=False,
                help_text="Was this communication automatically generated by MuckRock",
            ),
        ),
        migrations.AlterField(
            model_name="foiacommunication",
            name="communication",
            field=models.TextField(
                blank=True, help_text="The body text of the communication"
            ),
        ),
        migrations.AlterField(
            model_name="foiacommunication",
            name="datetime",
            field=models.DateTimeField(
                db_index=True,
                help_text="Timestamp for when this communication was sent",
            ),
        ),
        migrations.AlterField(
            model_name="foiacommunication",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("submitted", "Processing"),
                    ("ack", "Awaiting Acknowledgement"),
                    ("processed", "Awaiting Response"),
                    ("appealing", "Awaiting Appeal"),
                    ("fix", "Fix Required"),
                    ("payment", "Payment Required"),
                    ("lawsuit", "In Litigation"),
                    ("rejected", "Rejected"),
                    ("no_docs", "No Responsive Documents"),
                    ("done", "Completed"),
                    ("partial", "Partially Completed"),
                    ("abandoned", "Withdrawn"),
                ],
                help_text="The status the request was set to for this communication",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="foiacommunication",
            name="subject",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The subject line for this communication",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="foiarequest",
            name="agency",
            field=models.ForeignKey(
                help_text="The government agency the request was filed with",
                on_delete=django.db.models.deletion.PROTECT,
                to="agency.agency",
            ),
        ),
        migrations.AlterField(
            model_name="foiarequest",
            name="datetime_done",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp of when this request was completed",
                null=True,
                verbose_name="Date response received",
            ),
        ),
        migrations.AlterField(
            model_name="foiarequest",
            name="datetime_updated",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp of the latest communication",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="foiarequest",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default="0.00",
                help_text="The price associated with any payment this request requires",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="foiarequest",
            name="slug",
            field=models.SlugField(
                help_text="The slug is generated from the title and used in the request URL",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="foiarequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Processing"),
                    ("ack", "Awaiting Acknowledgement"),
                    ("processed", "Awaiting Response"),
                    ("appealing", "Awaiting Appeal"),
                    ("fix", "Fix Required"),
                    ("payment", "Payment Required"),
                    ("lawsuit", "In Litigation"),
                    ("rejected", "Rejected"),
                    ("no_docs", "No Responsive Documents"),
                    ("done", "Completed"),
                    ("partial", "Partially Completed"),
                    ("abandoned", "Withdrawn"),
                ],
                db_index=True,
                help_text="The current status of the request",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="foiarequest",
            name="title",
            field=models.CharField(
                db_index=True, help_text="Title of the request", max_length=1024
            ),
        ),
    ]
