# Generated by Django 4.2 on 2024-09-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0106_merge_20240604_1047"),
        ("foia", "0108_remove_foiacomposer_embargo_and_more"),
    ]

    operations = []
