# Generated by Django 4.2 on 2025-02-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0109_foiarequest_disable_gloo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foiarequest",
            name="disable_gloo",
            field=models.BooleanField(
                default=False,
                help_text="Do not run gloo to automatically categorize communications to this request",
            ),
        ),
    ]
