# Generated by Django 4.2 on 2025-03-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0110_alter_foiarequest_disable_gloo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foiacommunication",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("submitted", "Processing"),
                    ("ack", "Awaiting Acknowledgement"),
                    ("processed", "Awaiting Response"),
                    ("appealing", "Awaiting Appeal"),
                    ("fix", "Fix Required"),
                    ("payment", "Payment Required"),
                    ("lawsuit", "In Litigation"),
                    ("rejected", "Rejected"),
                    ("no_docs", "No Responsive Documents"),
                    ("done", "Completed"),
                    ("partial", "Partially Completed"),
                    ("abandoned", "Withdrawn"),
                    ("consolidated", "Consolidated"),
                ],
                help_text="The status the request was set to for this communication",
                max_length=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="foialogentry",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("submitted", "Processing"),
                    ("ack", "Awaiting Acknowledgement"),
                    ("processed", "Awaiting Response"),
                    ("appealing", "Awaiting Appeal"),
                    ("fix", "Fix Required"),
                    ("payment", "Payment Required"),
                    ("lawsuit", "In Litigation"),
                    ("rejected", "Rejected"),
                    ("no_docs", "No Responsive Documents"),
                    ("done", "Completed"),
                    ("partial", "Partially Completed"),
                    ("abandoned", "Withdrawn"),
                    ("consolidated", "Consolidated"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="foiarequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Processing"),
                    ("ack", "Awaiting Acknowledgement"),
                    ("processed", "Awaiting Response"),
                    ("appealing", "Awaiting Appeal"),
                    ("fix", "Fix Required"),
                    ("payment", "Payment Required"),
                    ("lawsuit", "In Litigation"),
                    ("rejected", "Rejected"),
                    ("no_docs", "No Responsive Documents"),
                    ("done", "Completed"),
                    ("partial", "Partially Completed"),
                    ("abandoned", "Withdrawn"),
                    ("consolidated", "Consolidated"),
                ],
                db_index=True,
                help_text="The current status of the request",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="foiasavedsearch",
            name="status",
            field=models.CharField(
                choices=[
                    ("", "-"),
                    ("submitted", "Processing"),
                    ("ack", "Awaiting Acknowledgement"),
                    ("processed", "Awaiting Response"),
                    ("appealing", "Awaiting Appeal"),
                    ("fix", "Fix Required"),
                    ("payment", "Payment Required"),
                    ("lawsuit", "In Litigation"),
                    ("rejected", "Rejected"),
                    ("no_docs", "No Responsive Documents"),
                    ("done", "Completed"),
                    ("partial", "Partially Completed"),
                    ("abandoned", "Withdrawn"),
                    ("consolidated", "Consolidated"),
                ],
                max_length=12,
            ),
        ),
    ]
