# Generated by Django 4.2 on 2025-03-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0109_merge_20240917_1215"),
        ("foia", "0110_alter_foiarequest_disable_gloo"),
    ]

    operations = []
