# Generated by Django 4.2 on 2025-03-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0111_alter_foiacommunication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiarequest',
            name='hide_portal_credentials',
            field=models.BooleanField(default=False),
        ),
    ]
