# Generated by Django 4.2 on 2025-05-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0112_foiarequest_hide_portal_credentials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foialogentry",
            name="date_requested",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="foiarequest",
            name="hide_portal_credentials",
            field=models.BooleanField(
                default=False,
                help_text="Do not show the requester the portal email and password on the request page.  This is useful to hide proxy IDs.",
            ),
        ),
    ]
