# Generated by Django 4.2 on 2025-04-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0111_merge_20250304_1025"),
        ("foia", "0112_foiarequest_hide_portal_credentials"),
    ]

    operations = []
