# Generated by Django 4.2 on 2025-08-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0113_alter_foialogentry_date_requested_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foiarequest",
            name="passcode",
        ),
    ]
