# Generated by Django 4.2 on 2025-07-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0113_alter_foialogentry_date_requested_and_more"),
        ("foia", "0113_merge_20250421_1123"),
    ]

    operations = []
