# Generated by Django 4.2 on 2026-01-29 21:01

# Django
from django.contrib.auth import get_user_model
from django.db import migrations

TEMPLATE = """
A quien le interese:

De conformidad con el derecho constitucional de acceso a la información pública, reconocido por el Tribunal Supremo de Puerto Rico en Soto v. Secretario de Justicia (1982), y bajo los parámetros de la Ley de Transparencia y Procedimiento Expedito para el Acceso a la Información Pública (2019), solicito los siguientes documentos:

{ requested docs }

{ waiver }

En caso de que se apliquen cargos, le agradecería que me informara del importe total antes de atender mi solicitud. Preferiría que la solicitud se completara electrónicamente, mediante un archivo adjunto por correo electrónico si está disponible, o en CD-ROM si no lo está.

Le agradezco de antemano su cooperación en este asunto. Espero recibir su respuesta a esta solicitud en un plazo de 10 días.

Atentamente,

{ name }
"""


def add_template(apps, schema_editor):
    FOIATemplate = apps.get_model("foia", "FOIATemplate")
    Jurisdiction = apps.get_model("jurisdiction", "Jurisdiction")
    User = get_user_model()

    puerto_rico = Jurisdiction.objects.filter(name="Puerto Rico", level="s").first()
    if puerto_rico is None:
        return
    muckrock_staff = User.objects.get(username="MuckrockStaff")

    FOIATemplate.objects.create(
        name="Puerto Rico",
        user=muckrock_staff,
        jurisdiction=puerto_rico,
        template=TEMPLATE,
    )


def remove_template(apps, schema_editor):
    FOIATemplate = apps.get_model("foia", "FOIATemplate")
    FOIATemplate.objects.filter(name="Puerto Rico").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0114_remove_foiarequest_passcode"),
        ("jurisdiction", "0032_auto_20260129_1545"),
    ]

    operations = [migrations.RunPython(add_template, remove_template)]
