# Generated by Django 5.2.12 on 2026-05-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0115_auto_20260129_1601"),
    ]

    operations = [
        migrations.AddField(
            model_name="foiarequest",
            name="embargo_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Custom message displayed in the embargo status section",
            ),
        ),
    ]
