# Generated by Django 5.2.12 on 2026-07-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0116_add_embargo_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foiacommunication",
            name="opened",
            field=models.BooleanField(
                default=False,
                help_text="DEPRECATED: If emailed, did we receive an open notification? If faxed, did we receive a confirmation?",
            ),
        ),
    ]
