# Generated by Django 5.2.12 on 2026-08-26 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0037_organization_members_organization_parent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationStats",
            fields=[
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="stats",
                        serialize=False,
                        to="organization.organization",
                    ),
                ),
                (
                    "last_request_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
        ),
    ]
