# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0002_auto_20150614_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date'], 'permissions': (('post', 'Can post questions and answers'),)},
        ),
    ]
