# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0003_auto_20171017_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date'], 'permissions': (('post', 'Can post questions and answers'), ('block', 'Can block other users'))},
        ),
    ]
