# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 20:39

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_failedfaxtask_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snailmailtask',
            name='category',
            field=models.CharField(
                choices=[('a', 'Appeal'), ('n', 'New'), ('u', 'Update'),
                         ('f', 'Followup')],
                max_length=1
            ),
        ),
    ]
