# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20160412_1804'),
        ('task', '0014_auto_20160330_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReviewTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task.Task')),
                ('explanation', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            bases=('task.task',),
        ),
    ]
