# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_projectreviewtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectreviewtask',
            name='explanation',
        ),
        migrations.AddField(
            model_name='projectreviewtask',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
