# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 12:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foia', '0019_auto_20160330_2039'),
        ('task', '0016_auto_20160421_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewExemptionTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task.Task')),
                ('language', models.TextField()),
                ('foia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foia.FOIARequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('task.task',),
        ),
    ]
