# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-11 09:13

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_newexemptiontask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snailmailtask',
            name='category',
            field=models.CharField(
                choices=[('a', 'Appeal'), ('n', 'New'), ('u', 'Update'),
                         ('f', 'Followup'), ('p', 'Payment')],
                max_length=1
            ),
        ),
    ]
