# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-11 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_newexemptiontask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snailmailtask',
            name='category',
            field=models.CharField(choices=[(b'a', b'Appeal'), (b'n', b'New'), (b'u', b'Update'), (b'f', b'Followup'), (b'p', b'Payment')], max_length=1),
        ),
    ]
