# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_reviewagencytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='snailmailtask',
            name='switch',
            field=models.BooleanField(default=False, help_text=b'Designates we have switched to sending to this address from another formof communication due to some sort of error.  A note should be included in the communication with an explanation.'),
        ),
    ]
