# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0040_foiacommunication_hidden'),
        ('task', '0021_snailmailtask_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task.Task')),
                ('category', models.CharField(choices=[(b'i', b'Incoming'), (b'n', b'New'), (b'u', b'Update'), (b'f', b'Followup')], max_length=1)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foia.FOIACommunication')),
            ],
            bases=('task.task',),
        ),
    ]
