# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 17:20

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0040_foiacommunication_hidden'),
        ('task', '0021_snailmailtask_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalTask',
            fields=[
                (
                    'task_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='task.Task'
                    )
                ),
                (
                    'category',
                    models.CharField(
                        choices=[('i', 'Incoming'), ('n', 'New'),
                                 ('u', 'Update'), ('f', 'Followup')],
                        max_length=1
                    )
                ),
                (
                    'communication',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='foia.FOIACommunication'
                    )
                ),
            ],
            bases=('task.task',),
        ),
    ]
