# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 11:19

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0022_portaltask'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaltask',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='portaltask',
            name='category',
            field=models.CharField(
                choices=[('i', 'Incoming'), ('a', 'Appeal'), ('n', 'New'),
                         ('u', 'Update'), ('f', 'Followup'), ('p', 'Payment')],
                max_length=1
            ),
        ),
    ]
