# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0023_auto_20171110_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_deferred',
            field=models.DateField(blank=True, null=True),
        ),
    ]
