# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 14:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0024_task_date_deferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='form_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
