# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0025_task_form_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaggedtask',
            name='category',
            field=models.TextField(blank=True, choices=[(b'move communication', b'A communication ended up on this request inappropriately'), (b'no response', b"This agency hasn't responded after multiple submissions."), (b'wrong agency', b'The agency has indicated that this request should be directed to another agency.'), (b'missing documents', b'I should have received documents for this request.'), (b'form', b'The agency has asked that you use a form.'), (b'follow-up complaints', b'Agency is complaining about follow-up messages.'), (b'appeal', b'Should I appeal this response?'), (b'proxy', b'The agency denied the request due to an in-state citzenship law.')]),
        ),
    ]
