# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 17:33

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0025_task_form_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaggedtask',
            name='category',
            field=models.TextField(
                blank=True,
                choices=[(
                    'move communication',
                    'A communication ended up on this request inappropriately'
                ), (
                    'no response',
                    "This agency hasn't responded after multiple submissions."
                ), (
                    'wrong agency',
                    'The agency has indicated that this request should be directed to another agency.'
                ), (
                    'missing documents',
                    'I should have received documents for this request.'
                ), ('form', 'The agency has asked that you use a form.'), (
                    'follow-up complaints',
                    'Agency is complaining about follow-up messages.'
                ), ('appeal', 'Should I appeal this response?'), (
                    'proxy',
                    'The agency denied the request due to an in-state citzenship law.'
                )]
            ),
        ),
    ]
