# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-30 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0059_auto_20180327_1157'),
        ('task', '0026_flaggedtask_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='multirequesttask',
            name='composer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foia.FOIAComposer'),
        ),
    ]
