# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-30 15:19
from __future__ import unicode_literals

# Django
from django.db import migrations


def convert_multitask(apps, schema_editor):
    MultiRequestTask = apps.get_model('task', 'MultiRequestTask')
    for task in MultiRequestTask.objects.all():
        task.composer = task.multirequest.composer
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0027_multirequesttask_composer'),
    ]

    operations = [migrations.RunPython(convert_multitask)]
