# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-30 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0028_auto_20180330_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multirequesttask',
            name='multirequest',
        ),
        migrations.AlterField(
            model_name='multirequesttask',
            name='composer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foia.FOIAComposer'),
        ),
    ]
