# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-29 16:10


# Django
from django.db import migrations


def convert_new_exemptions(apps, schema_editor):
    NewExemptionTask = apps.get_model('task', 'NewExemptionTask')
    FlaggedTask = apps.get_model('task', 'FlaggedTask')
    for task in NewExemptionTask.objects.filter(resolved=False):
        FlaggedTask.objects.create(
            date_created=task.date_created,
            date_done=task.date_done,
            date_deferred=task.date_deferred,
            resolved=task.resolved,
            assigned=task.assigned,
            resolved_by=task.resolved_by,
            form_data=task.form_data,
            text=task.language,
            user=task.user,
            foia=task.foia,
            category='appeal',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0030_auto_20180420_1013'),
    ]

    operations = [migrations.RunPython(convert_new_exemptions)]
