# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-16 16:01

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0032_auto_20180713_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaggedtask',
            name='category',
            field=models.TextField(
                blank=True,
                choices=[(
                    'move communication',
                    'A communication ended up on this request inappropriately.'
                ), (
                    'no response',
                    "This agency hasn't responded after multiple submissions."
                ), (
                    'wrong agency',
                    'The agency has indicated that this request should be directed to another agency.'
                ), (
                    'missing documents',
                    'I should have received documents for this request.'
                ), ('form', 'The agency has asked that you use a form.'), (
                    'follow-up complaints',
                    'Agency is complaining about follow-up messages.'
                ), ('appeal', 'Should I appeal this response?'), (
                    'proxy',
                    'The agency denied the request due to an in-state citzenship law.'
                ), ('contact info changed', 'User supplied contact info.'), (
                    'no proxy', 'No proxy was available.'
                ), (
                    'agency update',
                    'An agency logged in to the site and updated a request.'
                ), (
                    'agency new email',
                    'An agency with no primary email set replied via email.'
                ), (
                    'manual form',
                    'A request needs a PDF form to be manually filled out to be submitted'
                )]
            ),
        ),
    ]
