# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-11 15:02


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0033_auto_20181016_1201'),
        ('task', '0034_auto_20181204_2207'),
    ]

    operations = [
    ]
