# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-01 21:01


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0035_auto_20181219_1018'),
        ('task', '0035_merge_20181211_1002'),
    ]

    operations = [
    ]
