# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 16:58


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0036_merge_20190201_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsetask',
            name='scan',
            field=models.BooleanField(default=False),
        ),
    ]
