# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-16 19:15

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0037_responsetask_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='snailmailtask',
            name='reason',
            field=models.CharField(
                blank=True,
                choices=[
                    ('auto', 'Automatic Lob sending was disabled'),
                    ('addr',
                     'FOIA had no address'), ('appeal', 'This is an appeal'),
                    ('pay', 'This is a payment'),
                    ('pdf', 'There was an error processing the PDF'),
                    ('page', 'The PDF was over the page limit'),
                    ('attm', 'There was an error processing an attachment'),
                    ('lob', 'There was an error sending via Lob')
                ],
                help_text=
                'Reason the snail mail task was created instead of auto sending via lob',
                max_length=6
            ),
        ),
    ]
