# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-04 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0040_snailmailtask_error_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snailmailtask',
            name='reason',
            field=models.CharField(blank=True, choices=[(b'auto', b'Automatic Lob sending was disabled'), (b'addr', b'FOIA had no address'), (b'appeal', b'This is an appeal'), (b'pay', b'This is a payment'), (b'limit', b'Over the payment limit'), (b'pdf', b'There was an error processing the PDF'), (b'page', b'The PDF was over the page limit'), (b'attm', b'There was an error processing an attachment'), (b'lob', b'There was an error sending via Lob')], help_text=b'Reason the snail mail task was created instead of auto sending via lob', max_length=6),
        ),
    ]
