# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-07 18:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0042_auto_20191209_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdfundtask',
            name='crowdfund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crowdfund.Crowdfund'),
        ),
        migrations.AlterField(
            model_name='failedfaxtask',
            name='communication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foia.FOIACommunication'),
        ),
        migrations.AlterField(
            model_name='flaggedtask',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.Agency'),
        ),
        migrations.AlterField(
            model_name='flaggedtask',
            name='foia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='foia.FOIARequest'),
        ),
        migrations.AlterField(
            model_name='flaggedtask',
            name='jurisdiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jurisdiction.Jurisdiction'),
        ),
        migrations.AlterField(
            model_name='flaggedtask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='multirequesttask',
            name='composer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foia.FOIAComposer'),
        ),
        migrations.AlterField(
            model_name='newagencytask',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agency.Agency'),
        ),
        migrations.AlterField(
            model_name='newagencytask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newexemptiontask',
            name='foia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foia.FOIARequest'),
        ),
        migrations.AlterField(
            model_name='newexemptiontask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newportaltask',
            name='communication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foia.FOIACommunication'),
        ),
        migrations.AlterField(
            model_name='orphantask',
            name='communication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foia.FOIACommunication'),
        ),
        migrations.AlterField(
            model_name='paymentinfotask',
            name='communication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foia.FOIACommunication'),
        ),
        migrations.AlterField(
            model_name='portaltask',
            name='communication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foia.FOIACommunication'),
        ),
        migrations.AlterField(
            model_name='projectreviewtask',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.Project'),
        ),
        migrations.AlterField(
            model_name='rejectedemailtask',
            name='foia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='foia.FOIARequest'),
        ),
        migrations.AlterField(
            model_name='responsetask',
            name='communication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foia.FOIACommunication'),
        ),
        migrations.AlterField(
            model_name='reviewagencytask',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agency.Agency'),
        ),
        migrations.AlterField(
            model_name='snailmailtask',
            name='communication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foia.FOIACommunication'),
        ),
        migrations.AlterField(
            model_name='snailmailtask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staleagencytask',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agency.Agency'),
        ),
        migrations.AlterField(
            model_name='statuschangetask',
            name='foia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foia.FOIARequest'),
        ),
        migrations.AlterField(
            model_name='statuschangetask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
