# Generated by Django 2.2.15 on 2020-08-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0043_auto_20200707_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newagencytask',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Agency'),
        ),
    ]
