# Generated by Django 2.2.15 on 2021-07-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0048_auto_20210628_1540'),
        ('task', '0048_auto_20210707_0931'),
    ]

    operations = [
    ]
