# Generated by Django 2.2.15 on 2021-07-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0049_merge_20210719_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewagencytask',
            name='source',
            field=models.CharField(blank=True, choices=[('staff', 'Staff Review'), ('stale', 'Stale Request'), ('email', 'Bad Email'), ('fax', 'Bad Fax')], max_length=5, null=True),
        ),
    ]
