# Generated by Django 3.2.9 on 2021-12-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0050_reviewagencytask_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='form_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
