# Generated by Django 3.2.9 on 2023-01-11 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0094_foiacommunication_category'),
        ('task', '0051_alter_task_form_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaggedtask',
            name='foia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foia.foiarequest'),
        ),
    ]
