# Generated by Django 4.2 on 2023-05-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0052_alter_flaggedtask_foia"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="zendesk_ticket_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
