# Generated by Django 4.2 on 2024-04-10 14:15

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0004_alter_taggeditembase_content_type_and_more"),
        ("task", "0054_alter_flaggedtask_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="tags.TaggedItemBase",
                to="tags.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="flaggedtask",
            name="category",
            field=models.TextField(
                blank=True,
                choices=[
                    (
                        "move communication",
                        "A communication ended up on this request inappropriately.",
                    ),
                    (
                        "no response",
                        "This agency has not responded after multiple submissions.",
                    ),
                    (
                        "wrong agency",
                        "The agency has indicated that this request should be directed to another agency.",
                    ),
                    (
                        "missing documents",
                        "The agency mailed documents but I do not see them on this request",
                    ),
                    ("portal help", "I need help with a portal, link or login"),
                    (
                        "form",
                        "The agency has asked that I fill out or sign a PDF form.",
                    ),
                    (
                        "follow-up complaints",
                        "Agency is complaining about follow-up messages.",
                    ),
                    ("appeal", "Should I appeal this response?"),
                    (
                        "proxy",
                        "The agency denied the request due to an in-state citzenship law.",
                    ),
                    ("payment", "There is an issue with my payment."),
                    ("contact info changed", "User supplied contact info."),
                    ("no proxy", "No proxy was available."),
                    (
                        "agency login confirm",
                        "An agency used a secure login to update a request.",
                    ),
                    (
                        "agency login validate",
                        "An agency used an insecure login to update a request.",
                    ),
                    (
                        "agency new email",
                        "An agency with no primary email set replied via email.",
                    ),
                    (
                        "manual form",
                        "A request needs a PDF form to be manually filled out to be submitted",
                    ),
                    ("foiaonline", "The FOIAOnline autologin failed"),
                    ("govqa", "The GovQA scraper failed"),
                    (
                        "download file",
                        "This request contains a link to a file to download",
                    ),
                    (
                        "portal payment",
                        "A payment has been paid which should be submitted via portal",
                    ),
                    ("already responded", "I already responded to this request"),
                    ("bad contact", "I am not the best contact for this request"),
                    ("wrong agency", "This request should go to a different agency"),
                ],
            ),
        ),
    ]
