# Generated by Django 4.2 on 2024-03-29 14:44

# Django
from django.db import migrations
from django.db.models.expressions import F


def communication_data(apps, schema_editor):
    PaymentInfoTask = apps.get_model("task", "PaymentInfoTask")
    for task in PaymentInfoTask.objects.all().select_related("communication"):
        task.user = task.communication.from_user
        task.foia = task.communication.foia
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0055_paymentinfotask_foia_paymentinfotask_user"),
    ]

    operations = [migrations.RunPython(communication_data, migrations.RunPython.noop)]
