# Generated by Django 4.2 on 2024-03-29 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0104_alter_foialogentry_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("task", "0056_auto_20240329_1044"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentinfotask",
            name="communication",
        ),
        migrations.AlterField(
            model_name="paymentinfotask",
            name="foia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="foia.foiarequest"
            ),
        ),
        migrations.AlterField(
            model_name="paymentinfotask",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
