# Generated by Django 4.2 on 2024-04-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0055_task_tags_alter_flaggedtask_category"),
        ("task", "0057_remove_paymentinfotask_communication_and_more"),
    ]

    operations = []
