# Generated by Django 4.2 on 2024-04-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0058_merge_20240411_1339"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
