# Generated by Django 5.2.12 on 2026-07-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0059_task_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsetask",
            name="predicted_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("submitted", "Processing"),
                    ("ack", "Awaiting Acknowledgement"),
                    ("processed", "Awaiting Response"),
                    ("appealing", "Awaiting Appeal"),
                    ("fix", "Fix Required"),
                    ("payment", "Payment Required"),
                    ("lawsuit", "In Litigation"),
                    ("rejected", "Rejected"),
                    ("no_docs", "No Responsive Documents"),
                    ("done", "Completed"),
                    ("partial", "Partially Completed"),
                    ("abandoned", "Withdrawn"),
                    ("consolidated", "Consolidated"),
                ],
                max_length=13,
                null=True,
            ),
        ),
    ]
