# Generated by Django 5.2.12 on 2026-09-02 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0029_alter_source_type"),
        ("task", "0059_task_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewagencytask",
            name="email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="review_tasks",
                to="communication.emailaddress",
            ),
        ),
    ]
