# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foia', '0036_auto_20170929_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(unique=True)),
                ('address_to', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmailCommunication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_datetime', models.DateTimeField()),
                ('confirmed_datetime', models.DateTimeField(blank=True, null=True)),
                ('cc_emails', models.ManyToManyField(related_name='cc_emails', to='communication.EmailAddress')),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='foia.FOIACommunication')),
                ('from_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_emails', to='communication.EmailAddress')),
                ('to_emails', models.ManyToManyField(related_name='to_emails', to='communication.EmailAddress')),
            ],
        ),
        migrations.CreateModel(
            name='EmailError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('code', models.CharField(max_length=10)),
                ('error', models.TextField(blank=True)),
                ('event', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=255)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='communication.EmailCommunication')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='communication.EmailAddress')),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='EmailOpen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=10)),
                ('client_type', models.CharField(max_length=15)),
                ('client_name', models.CharField(max_length=50)),
                ('client_os', models.CharField(max_length=10, verbose_name=b'Client OS')),
                ('device_type', models.CharField(max_length=10)),
                ('user_agent', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=15, verbose_name=b'IP Address')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opens', to='communication.EmailCommunication')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opens', to='communication.EmailAddress')),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='FaxCommunication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_datetime', models.DateTimeField()),
                ('confirmed_datetime', models.DateTimeField(blank=True, null=True)),
                ('fax_id', models.CharField(blank=True, default=b'', max_length=10)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faxes', to='foia.FOIACommunication')),
            ],
        ),
        migrations.CreateModel(
            name='FaxError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('error_type', models.CharField(blank=True, max_length=255)),
                ('error_code', models.CharField(blank=True, max_length=255)),
                ('error_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='communication.FaxCommunication')),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='MailCommunication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_datetime', models.DateTimeField()),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mails', to='foia.FOIACommunication')),
                ('from_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_mails', to='communication.Address')),
                ('to_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_mails', to='communication.Address')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('type', models.CharField(choices=[(b'fax', b'Fax'), (b'phone', b'Phone')], default=b'phone', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='WebCommunication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_datetime', models.DateTimeField()),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_comms', to='foia.FOIACommunication')),
            ],
        ),
        migrations.AddField(
            model_name='faxerror',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='communication.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='faxcommunication',
            name='to_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communication.PhoneNumber'),
        ),
    ]
