# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_portalcommunication_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailcommunication',
            name='pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=b'snail_pdfs/%Y/%m/%d', verbose_name=b'PDF'),
        ),
    ]
