# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_mailcommunication_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_to',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.AddField(
            model_name='address',
            name='agency_override',
            field=models.CharField(blank=True, help_text=b'Override the agency this is addressed to', max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='attn_override',
            field=models.CharField(blank=True, help_text=b'Override the attention line to address this to a particular person', max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='suite',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=localflavor.us.models.USStateField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(blank=True),
        ),
    ]
