# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 11:14
from __future__ import unicode_literals

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_auto_20171122_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='point',
            #field=djgeojson.fields.PointField(blank=True),
            # changing so I can uninstall djgeojson, this field is later removed
            field=models.CharField(),
        ),
    ]
