# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_address_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
