# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_auto_20171129_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
