# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-13 18:57


# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0010_auto_20180307_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailcommunication',
            name='from_address',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='from_mails',
                to='communication.Address'
            ),
        ),
        migrations.AlterField(
            model_name='mailcommunication',
            name='to_address',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='to_mails',
                to='communication.Address'
            ),
        ),
    ]
