# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-13 17:40


# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0012_uniqify_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([(
                'street', 'suite', 'city', 'state', 'zip_code',
                'agency_override', 'attn_override', 'address'
            )]),
        ),
    ]
