# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-25 14:04


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0014_remove_address_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailopen',
            name='ip_address',
            field=models.CharField(max_length=45, verbose_name=b'IP Address'),
        ),
    ]
