# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-13 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0015_auto_20190325_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailcommunication',
            name='lob_id',
            field=models.CharField(blank=True, default=b'', max_length=20),
        ),
    ]
