# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-16 19:15


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0016_mailcommunication_lob_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('event', models.CharField(max_length=255)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='communication.MailCommunication')),
            ],
        ),
    ]
