# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-25 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0017_mailevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailevent',
            options={'ordering': ['datetime']},
        ),
    ]
