# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-04 14:45


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0069_auto_20190718_1424'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0025_remove_agency_payable_to'),
        ('communication', '0018_auto_20190925_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('cashed_datetime', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='agency.Agency')),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='foia.FOIACommunication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_datetime'],
            },
        ),
    ]
