# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-07 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0019_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='cashed_datetime',
        ),
        migrations.AddField(
            model_name='check',
            name='deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='number',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
