# Generated by Django 2.2.15 on 2021-06-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0021_auto_20200707_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='deposit_date',
            new_name='status_date',
        ),
        migrations.AddField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('deposited', 'Deposited'), ('returned', 'Returned'), ('cancelled', 'Cancelled'), ('lost', 'Lost')], default='pending', max_length=9),
        ),
    ]
