# Generated by Django 2.2.15 on 2021-06-28 20:30

# Django
from django.db import migrations


def set_status(apps, schema_editor):
    """Set the status to deposited for checks with dates set"""
    Check = apps.get_model("communication", "Check")
    Check.objects.exclude(status_date=None).update(status="deposited")


class Migration(migrations.Migration):

    dependencies = [("communication", "0022_auto_20210628_1540")]

    operations = [migrations.RunPython(set_status, migrations.RunPython.noop)]
