# Generated by Django 2.2.15 on 2021-09-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0023_auto_20210628_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcommunication',
            name='message_id',
            field=models.TextField(blank=True),
        ),
    ]
