# Generated by Django 3.2.9 on 2022-08-09 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0026_auto_20220809_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='emailaddress',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='sources',
        ),
        migrations.AddField(
            model_name='source',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='communication.address'),
        ),
        migrations.AddField(
            model_name='source',
            name='email_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='communication.emailaddress'),
        ),
        migrations.AddField(
            model_name='source',
            name='phone_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='communication.phonenumber'),
        ),
    ]
