# Generated by Django 3.2.9 on 2022-08-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0027_auto_20220809_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['-datetime']},
        ),
    ]
