# Generated by Django 5.2.12 on 2026-08-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0029_alter_source_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailaddress",
            name="no_reply",
            field=models.BooleanField(
                default=False,
                help_text="Set this email as a no-reply manually so that we won't try to follow up to communications sent from this email",
            ),
        ),
    ]
