"""
Miscellanous utilities
"""

import actstream
import datetime
import mock
import random
import string
import stripe

from django.contrib.auth.models import User, Group
from django.core.cache import cache
from django.template import Context
from django.template.loader_tags import BlockNode, ExtendsNode


from muckrock.accounts.models import Notification

#From http://stackoverflow.com/questions/2687173/django-how-can-i-get-a-block-from-a-template

class BlockNotFound(Exception):
    """Block not found exception"""
    pass

def get_node(template, context=Context(), name='subject'):
    """Render one block from a template"""
    for node in template:
        if isinstance(node, BlockNode) and node.name == name:
            return node.render(context)
        elif isinstance(node, ExtendsNode):
            return get_node(node.nodelist, context, name)
    raise BlockNotFound("Node '%s' could not be found in template." % name)

def new_action(actor, verb, action_object=None, target=None, public=True, description=None):
    """Wrapper to send a new action and return the generated Action object."""
    action_signal = actstream.action.send(
        actor,
        verb=verb,
        action_object=action_object,
        target=target,
        public=public,
        description=description)
    # action_signal = ((action_handler, Action))
    return action_signal[0][1]

def notify(users, action):
    """Notify a set of users about an action and return the list of notifications."""
    notifications = []
    if isinstance(users, Group):
        # If users is a group, get the queryset of users
        users = users.user_set.all()
    elif isinstance(users, User):
        # If users is a single user, make it into a list
        users = [users]
    for user in users:
        notification = Notification.objects.create(user=user, action=action)
        notifications.append(notification)
    return notifications

def generate_key(size=6, chars=string.ascii_uppercase + string.digits):
    """Generates a random alphanumeric key"""
    return ''.join(random.SystemRandom().choice(chars) for _ in range(size))

def mock_middleware(request):
    """Mocks the request with messages and session middleware"""
    setattr(request, 'session', mock.MagicMock())
    setattr(request, '_messages', mock.MagicMock())
    return request

def get_stripe_token(card_number='4242424242424242'):
    """
    Helper function for creating a dummy Stripe token.
    Normally, the token would be generated by Stripe Checkout on the front end.
    Allows a different card number to be passed in to simulate different error cases.
    """
    card = {
        "number": card_number,
        "exp_month": datetime.date.today().month,
        "exp_year": datetime.date.today().year,
        "cvc": '123'
    }
    token = stripe.Token.create(card=card)
    # all we need for testing stripe calls is the token id
    return token.id

def cache_get_or_set(key, update, timeout):
    """Get the value from the cache if present, otherwise update it"""
    value = cache.get(key)
    if value is None:
        value = update()
        cache.set(key, value, timeout)
    return value
