# Generated by Django 4.2.27 on 2025-12-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JurisdictionResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction_id', models.IntegerField(help_text='ID from main MuckRock jurisdiction table')),
                ('jurisdiction_abbrev', models.CharField(help_text='State abbreviation (e.g., CO, GA, TN)', max_length=5)),
                ('file', models.FileField(help_text='Text or Markdown file with state-specific FOIA knowledge', upload_to='foia_coach/jurisdiction_resources/%Y/%m/')),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('gemini_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('gemini_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('index_status', models.CharField(choices=[('pending', 'Pending Upload'), ('uploading', 'Uploading'), ('indexing', 'Indexing'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20)),
                ('resource_type', models.CharField(choices=[('law_guide', 'Law Guide'), ('request_tips', 'Request Tips'), ('exemptions', 'Exemptions Guide'), ('agency_info', 'Agency Information'), ('case_law', 'Case Law'), ('general', 'General Information')], default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'foia_coach_jurisdictionresource',
                'ordering': ['jurisdiction_abbrev', 'order', 'display_name'],
                'indexes': [models.Index(fields=['jurisdiction_abbrev'], name='foia_coach__jurisdi_d1ecd9_idx'), models.Index(fields=['jurisdiction_id'], name='foia_coach__jurisdi_b232fe_idx')],
            },
        ),
    ]
