# Generated by Django 4.2.27 on 2025-12-12 15:12

from django.db import migrations, models


def migrate_gemini_data_forward(apps, schema_editor):
    """
    Migrate existing Gemini data to provider-agnostic fields.

    For resources with gemini_file_id:
    - Set provider='gemini'
    - Copy gemini_file_id to provider_file_id
    """
    JurisdictionResource = apps.get_model('jurisdiction', 'JurisdictionResource')

    # Update resources that have gemini_file_id
    resources_with_gemini = JurisdictionResource.objects.filter(
        gemini_file_id__isnull=False
    ).exclude(gemini_file_id='')

    count = resources_with_gemini.update(
        provider='gemini',
        provider_file_id=models.F('gemini_file_id')
    )

    if count > 0:
        print(f"Migrated {count} resources from Gemini-specific to provider-agnostic fields")


def migrate_gemini_data_backward(apps, schema_editor):
    """
    Reverse migration: copy provider_file_id back to gemini_file_id for gemini provider.
    """
    JurisdictionResource = apps.get_model('jurisdiction', 'JurisdictionResource')

    # Update resources that have provider='gemini'
    resources_with_gemini = JurisdictionResource.objects.filter(
        provider='gemini',
        provider_file_id__isnull=False
    ).exclude(provider_file_id='')

    count = resources_with_gemini.update(
        gemini_file_id=models.F('provider_file_id')
    )

    if count > 0:
        print(f"Restored {count} resources to Gemini-specific fields")


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurisdictionresource',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('mock', 'Mock (Testing)')], default='openai', help_text='RAG provider used for this resource', max_length=20),
        ),
        migrations.AddField(
            model_name='jurisdictionresource',
            name='provider_file_id',
            field=models.CharField(blank=True, help_text='Provider-specific file/document ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jurisdictionresource',
            name='provider_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Provider-specific metadata'),
        ),
        migrations.AddField(
            model_name='jurisdictionresource',
            name='provider_store_id',
            field=models.CharField(blank=True, help_text='Provider-specific store/vector store ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jurisdictionresource',
            name='gemini_display_name',
            field=models.CharField(blank=True, help_text='DEPRECATED: Kept for backward compatibility', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jurisdictionresource',
            name='gemini_file_id',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use provider_file_id instead', max_length=255, null=True),
        ),
        # Data migration: copy existing Gemini data to provider-agnostic fields
        migrations.RunPython(
            migrate_gemini_data_forward,
            reverse_code=migrate_gemini_data_backward
        ),
    ]
