# Generated by Django 4.2.27 on 2025-12-12 20:00

from django.db import migrations, models
import django.db.models.deletion


def migrate_existing_uploads_forward(apps, schema_editor):
    """
    Migrate existing provider upload data to ResourceProviderUpload model.
    Only creates records for the provider each resource was originally uploaded to.
    """
    JurisdictionResource = apps.get_model('jurisdiction', 'JurisdictionResource')
    ResourceProviderUpload = apps.get_model('jurisdiction', 'ResourceProviderUpload')

    # Only migrate resources that have provider data
    resources = JurisdictionResource.objects.exclude(
        provider=''
    ).exclude(
        provider__isnull=True
    )

    uploads_to_create = []
    for resource in resources:
        uploads_to_create.append(ResourceProviderUpload(
            resource=resource,
            provider=resource.provider,
            provider_file_id=resource.provider_file_id or '',
            provider_store_id=resource.provider_store_id or '',
            provider_metadata=resource.provider_metadata or {},
            index_status=resource.index_status or 'not_uploaded',
            indexed_at=resource.indexed_at,
            created_at=resource.created_at,
            updated_at=resource.updated_at
        ))

    if uploads_to_create:
        ResourceProviderUpload.objects.bulk_create(uploads_to_create)
        print(f"Created {len(uploads_to_create)} ResourceProviderUpload records")
    else:
        print("No existing provider data to migrate")


def migrate_existing_uploads_backward(apps, schema_editor):
    """
    Reverse migration: copy ResourceProviderUpload data back to JurisdictionResource.
    Uses the first upload record for each resource (arbitrary choice for rollback).
    """
    JurisdictionResource = apps.get_model('jurisdiction', 'JurisdictionResource')
    ResourceProviderUpload = apps.get_model('jurisdiction', 'ResourceProviderUpload')

    count = 0
    for resource in JurisdictionResource.objects.all():
        # Get first upload for this resource (if any)
        upload = ResourceProviderUpload.objects.filter(resource=resource).first()
        if upload:
            resource.provider = upload.provider
            resource.provider_file_id = upload.provider_file_id
            resource.provider_store_id = upload.provider_store_id
            resource.provider_metadata = upload.provider_metadata
            resource.index_status = upload.index_status
            resource.indexed_at = upload.indexed_at
            resource.save(update_fields=[
                'provider', 'provider_file_id', 'provider_store_id',
                'provider_metadata', 'index_status', 'indexed_at'
            ])
            count += 1

    if count > 0:
        print(f"Restored provider data to {count} JurisdictionResource records")
    else:
        print("No upload data to restore")


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0002_jurisdictionresource_provider_and_more'),
    ]

    operations = [
        # Create the new ResourceProviderUpload model
        migrations.CreateModel(
            name='ResourceProviderUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('mock', 'Mock (Testing)')], help_text='RAG provider for this upload', max_length=20)),
                ('provider_file_id', models.CharField(blank=True, help_text='Provider-specific file/document ID', max_length=255)),
                ('provider_store_id', models.CharField(blank=True, help_text='Provider-specific store/vector store ID', max_length=255)),
                ('provider_metadata', models.JSONField(blank=True, default=dict, help_text='Provider-specific metadata')),
                ('index_status', models.CharField(choices=[('not_uploaded', 'Not Uploaded'), ('pending', 'Pending Upload'), ('uploading', 'Uploading'), ('indexing', 'Indexing'), ('ready', 'Ready'), ('error', 'Error')], default='not_uploaded', help_text='Upload and indexing status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if upload failed')),
                ('indexed_at', models.DateTimeField(blank=True, help_text='When the resource was successfully indexed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(help_text='The resource being uploaded', on_delete=django.db.models.deletion.CASCADE, related_name='provider_uploads', to='jurisdiction.jurisdictionresource')),
            ],
            options={
                'db_table': 'foia_coach_resourceproviderupload',
                'ordering': ['provider'],
                'unique_together': {('resource', 'provider')},
            },
        ),
        # Add indexes for ResourceProviderUpload
        migrations.AddIndex(
            model_name='resourceproviderupload',
            index=models.Index(fields=['provider', 'index_status'], name='foia_coach__provide_abc123_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceproviderupload',
            index=models.Index(fields=['resource', 'provider'], name='foia_coach__resourc_def456_idx'),
        ),
        # Migrate data from JurisdictionResource to ResourceProviderUpload
        migrations.RunPython(
            migrate_existing_uploads_forward,
            reverse_code=migrate_existing_uploads_backward
        ),
        # Update deprecated field help text
        migrations.AlterField(
            model_name='jurisdictionresource',
            name='gemini_display_name',
            field=models.CharField(blank=True, help_text='DEPRECATED: No longer used', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jurisdictionresource',
            name='gemini_file_id',
            field=models.CharField(blank=True, help_text='DEPRECATED: Migrated to ResourceProviderUpload model', max_length=255, null=True),
        ),
        # Remove provider fields from JurisdictionResource
        migrations.RemoveField(
            model_name='jurisdictionresource',
            name='index_status',
        ),
        migrations.RemoveField(
            model_name='jurisdictionresource',
            name='indexed_at',
        ),
        migrations.RemoveField(
            model_name='jurisdictionresource',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='jurisdictionresource',
            name='provider_file_id',
        ),
        migrations.RemoveField(
            model_name='jurisdictionresource',
            name='provider_metadata',
        ),
        migrations.RemoveField(
            model_name='jurisdictionresource',
            name='provider_store_id',
        ),
    ]
