# Generated by Django 4.2.27 on 2025-12-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0003_multi_provider_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceproviderupload',
            name='index_status',
            field=models.CharField(
                choices=[
                    ('not_uploaded', 'Not Uploaded'),
                    ('pending', 'Pending Upload'),
                    ('uploading', 'Uploading'),
                    ('indexing', 'Indexing'),
                    ('ready', 'Ready'),
                    ('error', 'Error')
                ],
                default='pending',
                help_text='Upload and indexing status (defaults to pending to trigger automatic upload)',
                max_length=20
            ),
        ),
    ]
