# Generated by Django 4.2.27 on 2025-12-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdiction', '0004_auto_trigger_uploads'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='resourceproviderupload',
            new_name='foia_coach__provide_7d24b4_idx',
            old_name='foia_coach__provide_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='resourceproviderupload',
            new_name='foia_coach__resourc_a2aff8_idx',
            old_name='foia_coach__resourc_def456_idx',
        ),
        migrations.AlterField(
            model_name='jurisdictionresource',
            name='file',
            field=models.FileField(help_text='Text or Markdown file with state-specific FOIA knowledge', max_length=255, upload_to='foia_coach/jurisdiction_resources/%Y/%m/'),
        ),
    ]
