# Generated by Django 4.2 on 2026-02-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jurisdiction", "0005_increase_file_field_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExampleResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jurisdiction_abbrev",
                    models.CharField(
                        blank=True,
                        help_text="State abbreviation (e.g., CO, GA). Leave blank for global examples.",
                        max_length=5,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short descriptive title for admin reference",
                        max_length=255,
                    ),
                ),
                ("user_question", models.TextField(help_text="Example user question")),
                (
                    "assistant_response",
                    models.TextField(
                        help_text="Ideal assistant response demonstrating desired format and quality"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "foia_coach_exampleresponse",
                "ordering": ["order", "title"],
            },
        ),
        migrations.AddIndex(
            model_name="exampleresponse",
            index=models.Index(
                fields=["jurisdiction_abbrev", "is_active"],
                name="foia_coach__jurisdi_747e12_idx",
            ),
        ),
    ]
