# Generated by Django 4.2 on 2026-02-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jurisdiction", "0006_add_example_response"),
    ]

    operations = [
        migrations.CreateModel(
            name="NFOICPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jurisdiction_abbrev",
                    models.CharField(
                        help_text="State abbreviation (e.g., CO, GA). Partners are always state-specific.",
                        max_length=5,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Organization name", max_length=255),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, help_text="Organization website URL", max_length=500
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Contact email address", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Contact phone number", max_length=50
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="What they do, services offered"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "foia_coach_nfoicpartner",
                "ordering": ["jurisdiction_abbrev", "order", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="nfoicpartner",
            index=models.Index(
                fields=["jurisdiction_abbrev", "is_active"],
                name="foia_coach__jurisdi_6eaa15_idx",
            ),
        ),
    ]
