# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 20:39
from __future__ import unicode_literals

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='center',
            field=djgeojson.fields.PointField(default=b'{"type": "Point", "coordinates": [37.8, -96.9]}'),
        ),
    ]
