# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-14 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0014_auto_20160228_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdfund',
            name='date_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
