# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-12 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0016_auto_20171130_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdfund',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
