# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-12 14:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0017_crowdfund_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdfund',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
