# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-07 18:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0018_auto_20180112_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdfundpayment',
            name='recurring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='crowdfund.RecurringCrowdfundPayment'),
        ),
        migrations.AlterField(
            model_name='crowdfundpayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
