# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-03 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foiamachine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoiaMachineCommunication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('receiver', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('received', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='foiamachine.FoiaMachineRequest')),
            ],
        ),
    ]
