# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foiamachine', '0002_foiamachinecommunication'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiamachinerequest',
            name='sharing_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
