# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-11 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foiamachine', '0005_foiamachinerequest_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiamachinerequest',
            name='status',
            field=models.CharField(choices=[(b'started', b'Draft'), (b'submitted', b'Processing'), (b'ack', b'Awaiting Acknowledgement'), (b'processed', b'Awaiting Response'), (b'appealing', b'Awaiting Appeal'), (b'fix', b'Fix Required'), (b'payment', b'Payment Required'), (b'rejected', b'Rejected'), (b'no_docs', b'No Responsive Documents'), (b'done', b'Completed'), (b'partial', b'Partially Completed'), (b'abandoned', b'Withdrawn')], db_index=True, default='started', max_length=10),
        ),
    ]
