# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-11 15:13

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foiamachine', '0005_foiamachinerequest_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiamachinerequest',
            name='status',
            field=models.CharField(
                choices=[('started', 'Draft'), ('submitted', 'Processing'),
                         ('ack', 'Awaiting Acknowledgement'),
                         ('processed', 'Awaiting Response'),
                         ('appealing',
                          'Awaiting Appeal'), ('fix', 'Fix Required'),
                         ('payment',
                          'Payment Required'), ('rejected', 'Rejected'),
                         ('no_docs',
                          'No Responsive Documents'), ('done', 'Completed'),
                         ('partial',
                          'Partially Completed'), ('abandoned', 'Withdrawn')],
                db_index=True,
                default='started',
                max_length=10
            ),
        ),
    ]
