# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-12 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foiamachine', '0006_foiamachinerequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoiaMachineFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='foia_files/%Y/%m/%d', verbose_name='File')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='foiamachine.FoiaMachineCommunication')),
            ],
        ),
    ]
