# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-12 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foiamachine', '0007_foiamachinefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foiamachinefile',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='foiamachinecommunication',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='foiamachinecommunication',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='foiamachinefile',
            name='file',
            field=models.FileField(max_length=255, upload_to='foiamachine_files/%Y/%m/%d', verbose_name='File'),
        ),
    ]
