# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 13:34

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foiamachine', '0009_auto_20170220_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foiamachinerequest',
            name='status',
            field=models.CharField(
                choices=[('started', 'Draft'), ('submitted', 'Processing'),
                         ('ack', 'Awaiting Acknowledgement'),
                         ('processed', 'Awaiting Response'),
                         ('appealing',
                          'Awaiting Appeal'), ('fix', 'Fix Required'),
                         ('payment', 'Payment Required'),
                         ('lawsuit', 'In Litigation'), ('rejected', 'Rejected'),
                         ('no_docs',
                          'No Responsive Documents'), ('done', 'Completed'),
                         ('partial',
                          'Partially Completed'), ('abandoned', 'Withdrawn')],
                db_index=True,
                default='started',
                max_length=10
            ),
        ),
    ]
