# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-07 18:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foiamachine', '0010_auto_20171004_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foiamachinerequest',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.Agency'),
        ),
        migrations.AlterField(
            model_name='foiamachinerequest',
            name='jurisdiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jurisdiction.Jurisdiction'),
        ),
        migrations.AlterField(
            model_name='foiamachinerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
