# Generated by Django 4.2 on 2025-03-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foiamachine", "0011_auto_20200707_1435"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foiamachinerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("started", "Draft"),
                    ("submitted", "Processing"),
                    ("ack", "Awaiting Acknowledgement"),
                    ("processed", "Awaiting Response"),
                    ("appealing", "Awaiting Appeal"),
                    ("fix", "Fix Required"),
                    ("payment", "Payment Required"),
                    ("lawsuit", "In Litigation"),
                    ("rejected", "Rejected"),
                    ("no_docs", "No Responsive Documents"),
                    ("done", "Completed"),
                    ("partial", "Partially Completed"),
                    ("abandoned", "Withdrawn"),
                    ("consolidated", "Consolidated"),
                ],
                db_index=True,
                default="started",
                max_length=12,
            ),
        ),
    ]
